mkdir PUweight
mkdir PUweight/ZH_M125_Summer11
mkdir PUweight/ZH_M125_Fall11
mkdir PUweight/Filtered125emu
mkdir PUweight/DY_PtZ
mkdir PUweight/DY_HF_PtZ
mkdir PUweight/DY_LF_PtZ
mkdir PUweight/DY_M50
mkdir PUweight/DY_HF_M50
mkdir PUweight/DY_LF_M50
mkdir PUweight/QCD_Pt120to170
mkdir PUweight/QCD_Pt170to300
mkdir PUweight/QCD_Pt300to470
mkdir PUweight/TTJets
mkdir PUweight/T_tW
mkdir PUweight/Tbar_tW
mkdir PUweight/WJets
mkdir PUweight/WW
mkdir PUweight/WZ
mkdir PUweight/ZZ
mkdir PUweight/All2011Run
