mkdir OpenCuts
mkdir OneBtag/ZH_M115
mkdir OneBtag/DYJetsToLL_PtZ
mkdir OneBtag/DYJetsToLL_M50
mkdir OneBtag/QCD_Pt120to170
mkdir OneBtag/QCD_Pt170to300
mkdir OneBtag/QCD_Pt300to470
mkdir OneBtag/TTJets
mkdir OneBtag/TTJets_60M
mkdir OneBtag/T_schannel
mkdir OneBtag/T_tchannel
mkdir OneBtag/T_tWchannel_DR
mkdir OneBtag/T_tWchannel_DS
mkdir OneBtag/Tbar_schannel
mkdir OneBtag/Tbar_tchannel
mkdir OneBtag/Tbar_tWchannel_DR
mkdir OneBtag/Tbar_tWchannel_DS
mkdir OneBtag/WJetsToLNu_Pt100
mkdir OneBtag/WJetsToLNu_PtW100
mkdir OneBtag/WJetsToLNu_TuneZ2
mkdir OneBtag/WW
mkdir OneBtag/WZJets
mkdir OneBtag/WZ
mkdir OneBtag/ZJetsToLL
mkdir OneBtag/ZJetsToNuNu
mkdir OneBtag/ZZJets
mkdir OneBtag/ZZ
