mkdir PUweight
mkdir PUweight/ZH_M115
mkdir PUweight/DYJetsToLL_PtZ
mkdir PUweight/DYJetsToLL_M50
mkdir PUweight/QCD_Pt120to170
mkdir PUweight/QCD_Pt170to300
mkdir PUweight/QCD_Pt300to470
mkdir PUweight/TTJets
mkdir PUweight/TTJets_60M
mkdir PUweight/T_schannel
mkdir PUweight/T_tchannel
mkdir PUweight/T_tWchannel_DR
mkdir PUweight/T_tWchannel_DS
mkdir PUweight/Tbar_schannel
mkdir PUweight/Tbar_tchannel
mkdir PUweight/Tbar_tWchannel_DR
mkdir PUweight/Tbar_tWchannel_DS
mkdir PUweight/WJetsToLNu_Pt100
mkdir PUweight/WJetsToLNu_PtW100
mkdir PUweight/WJetsToLNu_TuneZ2
mkdir PUweight/WW
mkdir PUweight/WZJets
mkdir PUweight/WZ
mkdir PUweight/ZJetsToLL
mkdir PUweight/ZJetsToNuNu
mkdir PUweight/ZZJets
mkdir PUweight/ZZ
