TriggerStudyMuon /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/ElectronHadRun2011APromptV6/AddedElectronHadRun2011APromptV6_V21.root TriggerStudy/PromptV6Muon.root TriggerStudy/PromptV6Muon > TriggerStudy/PromptV6Muon.out
TriggerStudyMuon /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/ElectronHadRun2011APromptV4/AddedElectronHadRun2011APromptV4_V21.root TriggerStudy/PromptV4Muon.root TriggerStudy/PromptV4Muon > TriggerStudy/PromptV4Muon.out
TriggerStudyMuon /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/ElectronHadRun2011AAug05ReReco/AddedElectronHadRun2011AAug05ReReco_V21.root TriggerStudy/AugMuon.root TriggerStudy/AugMuon > TriggerStudy/AugMuon.out
TriggerStudyMuon /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/SingleElectronRun2011AMay10ReReco/AddedSingleElectronRun2011AMay10ReReco_V21.root TriggerStudy/MayMuon.root TriggerStudy/MayMuon > TriggerStudy/MayMuon.out
TriggerStudyElectron /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/SingleMuon/AddedSingleMuon_V21.root TriggerStudy/MayElectron.root TriggerStudy/MayElectron > TriggerStudy/MayElectron.out
TriggerStudyElectron /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/SingleMu_Aug05ReReco/AddedSingleMu_Aug05ReReco_V21.root TriggerStudy/AugElectron.root TriggerStudy/AugElectron > TriggerStudy/AugElectron.out
TriggerStudyElectron /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/SingleMu_PromptRecoV4/AddedSingleMu_PromptRecoV4_V21.root TriggerStudy/PromptV4Electron.root TriggerStudy/PromptV4Electron > TriggerStudy/PromptV4Electron.out
TriggerStudyElectron /home/hep/wilken/emu21test/src/VHbbAnalysis/VHbbDataFormats/bin/SingleMu_PromptRecoV6/AddedSingleMu_PromptRecoV6_V21.root TriggerStudy/PromptV6Electron.root TriggerStudy/PromptV6Electron > TriggerStudy/PromptV6Electron.out
TriggerStudyMuon TriggerStudy/All2011ARunEleHad.root TriggerStudy/Run2011AMuon.root TriggerStudy/Run2011AMuon > TriggerStudy/Run2011AMuon.out
TriggerStudyElectron TriggerStudy/All2011ARunSingleMuon.root TriggerStudy/Run2011AElectron.root  TriggerStudy/Run2011AElectron >  TriggerStudy/Run2011AElectron.out
TriggerStudyMuon /home/hep/wilken/CMSSW_4_2_8_patch7/src/VHbbAnalysis/VHbbDataFormats/bin/ElectronHadRun2011B/ElectronHadRun2011B_V21.root TriggerStudy/Run2011BMuon.root TriggerStudy/Run2011BMuon > TriggerStudy/Run2011BMuon.out
TriggerStudyElectron /home/hep/wilken/CMSSW_4_2_8_patch7/src/VHbbAnalysis/VHbbDataFormats/bin/SingleMuon2011B/SingleMuon2011B_V21.root TriggerStudy/Run2011BElectron.root TriggerStudy/Run2011BElectron > TriggerStudy/Run2011BElectron.out
TriggerStudyElectron  TriggerStudy/All2011RunforSingleMuon.root TriggerStudy/AllRun2011Electron.root TriggerStudy/AllRun2011Electron > TriggerStudy/AllRun2011Electron.out
TriggerStudyMuon TriggerStudy/All2011RunforEleHad.root TriggerStudy/AllRun2011Muon.root TriggerStudy/AllRun2011Muon > TriggerStudy/AllRun2011Muon.out

