root -l WW_BDTCut.C
root -l ZZ_BDTCut.C
root -l WZ_BDTCut.C
root -l DYPtZ_LF_BDTCut.C
root -l DYPtZ_HF_BDTCut.C
root -l DYM50_LF_BDTCut.C
root -l DYM50_HF_BDTCut.C
root -l TTJets_BDTCut.C
root -l Fall_ZH115_BDTCut.C
root -l Tbar_tW_BDTCut.C
root -l T_tW_BDTCut.C
root -l Filtered_BDTCut.C
root -l WJets_BDTCut.C
