// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.0.4         [262148]
ROOT Release   : 5.26/00       [334336]
Creator        : rachelwilken
Date           : Mon Jan  9 13:33:34 2012
Host           : Darwin macphsft06.cern.ch 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386
Dir            : /Users/rachelwilken/root/tmva/test
Training events: 1749
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostBeta: "3.000000e-01" [Parameter for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "100" [Minimum number of events required in a leaf node (default: max(20, N_train/(Nvar^2)/10) ) ]
nCuts: "35" [Number of steps during node cut optimisation]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
MaxDepth: "3" [Max depth of the decision tree allowed]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UseNTrainEvents: "1749" [number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
PruneStrength: "-1.000000e+00" [Pruning strength]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Hmass                         Hmass                         Hmass                         H Mass                        GeV                               'F'    [33.7756080627,1045.68005371]
Hpt                           Hpt                           Hpt                           H PT                          GeV                               'F'    [100.000518799,654.357849121]
CSV0                          CSV0                          CSV0                          CSV 1                                                           'F'    [0.247978940606,1]
CSV1                          CSV1                          CSV1                          CSV 2                                                           'F'    [0.24405990541,0.999999940395]
Zpt                           Zpt                           Zpt                           Z #rightarrow #mu#mu p_{T}    GeV                               'F'    [100.009117126,666.105163574]
abs(deltaPhi(Hphi,Zphi))      hjjzmmdPhi                    hjjzmmdPhi                    H-Z #Delta #varphi            rad                               'F'    [0.223567128181,3.14150309563]
abs(jetEta1-jetEta0)          deltaEta                      deltaEta                      J-J Delta Eta                                                   'F'    [7.73072242737e-05,4.83690500259]
nJets-2                       numaddj                       numaddj                       Num Add Jets                                                    'F'    [0,1]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef NN
#define NN new BDT_DecisionTreeNode
#endif
   
#ifndef BDT_DecisionTreeNode__def
#define BDT_DecisionTreeNode__def
   
class BDT_DecisionTreeNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_DecisionTreeNode ( BDT_DecisionTreeNode* left,
                          BDT_DecisionTreeNode* right,
                          double cutValue, Bool_t cutType, int selector,
                          int nodeType, double purity, double response ) :
   fLeft    ( left     ),
   fRight   ( right    ),
   fCutValue( cutValue ),
   fCutType ( cutType  ),
   fSelector( selector ),
   fNodeType( nodeType ),
   fPurity  ( purity   ),
   fResponse( response ){}

   virtual ~BDT_DecisionTreeNode();

   // test event if it decends the tree at this node to the right
   virtual Bool_t GoesRight( const std::vector<double>& inputValues ) const;
   BDT_DecisionTreeNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual Bool_t GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_DecisionTreeNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_DecisionTreeNode*   fLeft;     // pointer to the left daughter node
   BDT_DecisionTreeNode*   fRight;    // pointer to the right daughter node
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   Bool_t                  fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fSelector; // index of variable used in node selection (decision tree)   
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
BDT_DecisionTreeNode::~BDT_DecisionTreeNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
Bool_t BDT_DecisionTreeNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   Bool_t result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
Bool_t BDT_DecisionTreeNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Hmass", "Hpt", "CSV0", "CSV1", "Zpt", "abs(deltaPhi(Hphi,Zphi))", "abs(jetEta1-jetEta0)", "nJets-2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 33.7756080627441;
      fVmax[0] = 1045.68005371094;
      fVmin[1] = 100.000518798828;
      fVmax[1] = 654.357849121094;
      fVmin[2] = 0.247978940606117;
      fVmax[2] = 1;
      fVmin[3] = 0.244059905409813;
      fVmax[3] = 0.999999940395355;
      fVmin[4] = 100.009117126465;
      fVmax[4] = 666.105163574219;
      fVmin[5] = 0.223567128181458;
      fVmax[5] = 3.14150309562683;
      fVmin[6] = 7.73072242736816e-05;
      fVmax[6] = 4.83690500259399;
      fVmin[7] = 0;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_DecisionTreeNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_DecisionTreeNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_DecisionTreeNode*)current->GetRight();
         else current=(BDT_DecisionTreeNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.71244278528158);
  fForest.push_back( 
NN(
0, 
0, 
0.664027, 0, -1, -1, 0.00330786,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.19871);
  fForest.push_back( 
NN(
0, 
0, 
0.664027, 0, -1, -1, 0.0180625,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.862825);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.640914,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.222988,-99) , 
0.72428, 1, 6, 0, 0.357466,-99) , 
NN(
0, 
0, 
80.5829, 0, -1, -1, 0.103273,-99) , 
166.051, 0, 4, 0, 0.150697,-99) , 
NN(
0, 
0, 
0.958221, 0, -1, -1, 0.0273052,-99) , 
0.580033, 0, 3, 0, 0.057487,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.655987);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.577441,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.118828,-99) , 
93.5375, 0, 0, 0, 0.33404,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.0661755,-99) , 
127.39, 1, 0, 0, 0.257275,-99) , 
NN(
0, 
0, 
0.958221, 0, -1, -1, 0.0623758,-99) , 
0.580033, 0, 3, 0, 0.114944,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.535585);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.57498,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.225449,-99) , 
147.184, 0, 4, 0, 0.33387,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.0422961,-99) , 
144.355, 1, 0, 0, 0.263212,-99) , 
NN(
0, 
0, 
0.410193, 0, -1, -1, 0.0833744,-99) , 
0.916442, 0, 2, 0, 0.158344,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.398723);
  fForest.push_back( 
NN(
0, 
0, 
146.209, 1, -1, -1, 0.209312,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.343066);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.554316,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.142061,-99) , 
0.667354, 0, 2, 0, 0.471347,-99) , 
NN(
0, 
0, 
0.564655, 0, -1, -1, 0.156472,-99) , 
83.6357, 0, 0, 0, 0.357841,-99) , 
NN(
0, 
0, 
0.832884, 0, -1, -1, 0.0669774,-99) , 
146.209, 1, 0, 0, 0.282853,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.276718);
  fForest.push_back( 
NN(
0, 
0, 
146.209, 1, -1, -1, 0.284471,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.256286);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.554296,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.282625,-99) , 
0.328105, 0, 3, 0, 0.479286,-99) , 
NN(
0, 
0, 
0.589668, 0, -1, -1, 0.206535,-99) , 
74.287, 0, 0, 0, 0.410586,-99) , 
NN(
0, 
0, 
0.832884, 0, -1, -1, 0.117711,-99) , 
146.209, 1, 0, 0, 0.343966,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.213098);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.521231,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.333271,-99) , 
88.2302, 0, 0, 0, 0.451563,-99) , 
NN(
0, 
0, 
140.009, 0, -1, -1, 0.18562,-99) , 
142.778, 1, 0, 0, 0.403122,-99) , 
NN(
0, 
0, 
147.74, 0, -1, -1, 0.150362,-99) , 
0.644879, 0, 2, 0, 0.346484,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.183338);
  fForest.push_back( 
NN(
0, 
0, 
1.478, 1, -1, -1, 0.351802,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.137935);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.50618,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.199209,-99) , 
2.68154, 0, 5, 0, 0.488632,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.214816,-99) , 
0.563402, 0, 2, 0, 0.447571,-99) , 
NN(
0, 
0, 
0.916442, 0, -1, -1, 0.218638,-99) , 
1.478, 1, 6, 0, 0.394653,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.163043);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.530285,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.415403,-99) , 
0.937629, 0, 2, 0, 0.468926,-99) , 
NN(
0, 
0, 
0.938039, 0, -1, -1, 0.283389,-99) , 
115.734, 0, 4, 0, 0.42667,-99) , 
NN(
0, 
0, 
0.832884, 0, -1, -1, 0.215268,-99) , 
146.209, 1, 0, 0, 0.384861,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.121771);
  fForest.push_back( 
NN(
0, 
0, 
146.209, 1, -1, -1, 0.399895,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.119292);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.526035,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.377809,-99) , 
68.0544, 0, 0, 0, 0.501836,-99) , 
NN(
0, 
0, 
0.938039, 0, -1, -1, 0.344591,-99) , 
115.734, 0, 4, 0, 0.467258,-99) , 
NN(
0, 
0, 
0.832884, 0, -1, -1, 0.267245,-99) , 
146.209, 1, 0, 0, 0.429443,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.11603);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.642196,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.470945,-99) , 
210.083, 0, 4, 0, 0.491546,-99) , 
NN(
0, 
0, 
127.218, 0, -1, -1, 0.335458,-99) , 
1.50622, 1, 6, 0, 0.461769,-99) , 
NN(
0, 
0, 
147.74, 0, -1, -1, 0.280748,-99) , 
0.644879, 0, 2, 0, 0.426839,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.099966);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.526907,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.30362,-99) , 
2.73903, 0, 5, 0, 0.513616,-99) , 
NN(
0, 
0, 
127.218, 0, -1, -1, 0.361798,-99) , 
1.50622, 1, 6, 0, 0.484987,-99) , 
NN(
0, 
0, 
147.74, 0, -1, -1, 0.304762,-99) , 
0.644879, 0, 2, 0, 0.450715,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0845441);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.648316,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.467192,-99) , 
253.989, 0, 1, 0, 0.477936,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.334701,-99) , 
0.480241, 0, 2, 0, 0.463139,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.255099,-99) , 
2.01542, 1, 6, 0, 0.444363,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0669263);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.513542,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.402283,-99) , 
2.91152, 0, 5, 0, 0.496542,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.353782,-99) , 
0.480241, 0, 2, 0, 0.481935,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.271494,-99) , 
2.01542, 1, 6, 0, 0.463225,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.122772);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
157.777, 0, -1, 1, 0.638967,-99) , 
NN(
0, 
0, 
187.786, 1, -1, -1, 0.465693,-99) , 
106.349, 0, 0, 0, 0.499679,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.783902,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.358911,-99) , 
1.00591, 1, 6, 0, 0.494848,-99) , 
NN(
0, 
0, 
2.02138, 1, -1, -1, 0.324518,-99) , 
0.958221, 0, 2, 0, 0.383254,-99) , 
118.101, 1, 0, 0, 0.456611,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.123874);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.607381,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.47032,-99) , 
0.558807, 0, 6, 0, 0.554226,-99) , 
NN(
0, 
0, 
106.95, 0, -1, -1, 0.406534,-99) , 
119.275, 0, 4, 0, 0.518432,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.648518,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.412656,-99) , 
0.979645, 0, 2, 0, 0.473376,-99) , 
NN(
0, 
0, 
151.272, 1, -1, -1, 0.319611,-99) , 
0.0277778, 1, 7, 0, 0.405058,-99) , 
118.101, 1, 0, 0, 0.476901,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.103391);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.624927,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.463067,-99) , 
90.7732, 0, 0, 0, 0.55008,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.608089,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.44149,-99) , 
85.1723, 1, 0, 0, 0.463749,-99) , 
0.878662, 1, 6, 0, 0.508847,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.516236,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.264218,-99) , 
147.74, 0, 4, 0, 0.383967,-99) , 
0.644879, 0, 2, 0, 0.486234,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.100114);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.569019,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.457186,-99) , 
68.8917, 0, 0, 0, 0.544346,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.565518,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.387076,-99) , 
0.391833, 1, 3, 0, 0.456066,-99) , 
118.101, 1, 0, 0, 0.513742,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.364355,-99) , 
0.540432, 0, 2, 0, 0.492975,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0736751);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.553759,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.479016,-99) , 
0.0277778, 1, 7, 0, 0.519642,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.540889,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.308163,-99) , 
106.994, 0, 4, 0, 0.44112,-99) , 
115.734, 0, 4, 0, 0.503581,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.345729,-99) , 
2.01542, 1, 6, 0, 0.490204,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0675663);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.669658,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.520622,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.375014,-99) , 
142.778, 1, 0, 0, 0.499899,-99) , 
253.989, 0, 1, 0, 0.509791,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.514753,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.291166,-99) , 
147.74, 0, 4, 0, 0.399916,-99) , 
0.644879, 0, 2, 0, 0.490061,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0523882);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.654544,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.506663,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.376834,-99) , 
175.971, 1, 1, 0, 0.487791,-99) , 
253.989, 0, 1, 0, 0.497425,-99) , 
NN(
0, 
0, 
121.894, 1, -1, -1, 0.3996,-99) , 
0.644879, 0, 2, 0, 0.479928,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0524894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0.601947, 0, -1, 1, 0.58774,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.500243,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.356786,-99) , 
146.209, 1, 0, 0, 0.477986,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.312625,-99) , 
106.972, 0, 4, 0, 0.461689,-99) , 
225.808, 0, 4, 0, 0.474404,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.103091);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0.601947, 0, -1, 1, 0.574966,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.66704,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.450002,-99) , 
0.412047, 1, 3, 0, 0.508112,-99) , 
NN(
0, 
0, 
114.031, 0, -1, -1, 0.409685,-99) , 
0.937332, 0, 2, 0, 0.454733,-99) , 
225.808, 0, 4, 0, 0.466833,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.105798);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.775009,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.517183,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.271399,-99) , 
2.91116, 0, 5, 0, 0.476801,-99) , 
0.785428, 1, 3, 0, 0.531159,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.673279,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.419282,-99) , 
0.394885, 1, 3, 0, 0.550545,-99) , 
NN(
0, 
0, 
115.422, 0, -1, -1, 0.429249,-99) , 
0.958221, 0, 2, 0, 0.458764,-99) , 
0.664027, 0, 3, 0, 0.481564,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.110449);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.571243,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.435039,-99) , 
0.790053, 1, 3, 0, 0.534251,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.537173,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.387986,-99) , 
143.923, 1, 4, 0, 0.450965,-99) , 
1.07618, 1, 6, 0, 0.505016,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.635524,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.360959,-99) , 
107.431, 0, 4, 0, 0.495327,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.296394,-99) , 
0.328053, 0, 3, 0, 0.425543,-99) , 
115.734, 0, 4, 0, 0.488926,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0491004);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.542137,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.48723,-99) , 
0.349171, 1, 3, 0, 0.505496,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.527209,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.348259,-99) , 
0.938039, 0, 2, 0, 0.440636,-99) , 
115.734, 0, 4, 0, 0.492428,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.379685,-99) , 
2.28413, 1, 6, 0, 0.485497,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.088021);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.75655,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.523317,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.335444,-99) , 
2.96865, 0, 5, 0, 0.483355,-99) , 
0.785428, 1, 3, 0, 0.532369,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.639073,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.441252,-99) , 
0.394885, 1, 3, 0, 0.542656,-99) , 
NN(
0, 
0, 
115.422, 0, -1, -1, 0.44609,-99) , 
0.958221, 0, 2, 0, 0.469438,-99) , 
0.664027, 0, 3, 0, 0.489232,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0574035);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
105.023, 0, -1, 1, 0.533042,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.510832,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.404143,-99) , 
153.363, 1, 1, 0, 0.467034,-99) , 
1.07618, 1, 6, 0, 0.510034,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.535518,-99) , 
NN(
0, 
0, 
107.781, 1, -1, -1, 0.375489,-99) , 
118.685, 0, 1, 0, 0.440012,-99) , 
115.734, 0, 4, 0, 0.496042,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0901322);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.653383,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.441217,-99) , 
0.727789, 1, 3, 0, 0.596845,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.643157,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.455334,-99) , 
3.13026, 0, 5, 0, 0.476936,-99) , 
3.00656, 1, 5, 0, 0.498143,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.554811,-99) , 
NN(
0, 
0, 
0.979111, 0, -1, -1, 0.360351,-99) , 
88.2768, 1, 0, 0, 0.429174,-99) , 
2.89834, 0, 5, 0, 0.48837,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0704279);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
2.97926, 0, -1, 1, 0.587337,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.520331,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.394758,-99) , 
83.7484, 0, 0, 0, 0.494246,-99) , 
3.00656, 1, 5, 0, 0.510621,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.574425,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.357704,-99) , 
0.643698, 1, 3, 0, 0.498392,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.304574,-99) , 
116.176, 0, 1, 0, 0.435112,-99) , 
2.89834, 0, 5, 0, 0.499955,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0546731);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.613965,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.494445,-99) , 
0.789167, 1, 2, 0, 0.51608,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.530917,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.372013,-99) , 
0.0277778, 1, 7, 0, 0.465297,-99) , 
118.101, 1, 0, 0, 0.49867,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.412199,-99) , 
0.456874, 0, 2, 0, 0.490289,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0978251);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
167.403, 0, -1, 1, 0.567408,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.524405,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.281281,-99) , 
165.666, 1, 1, 0, 0.479623,-99) , 
94.6435, 0, 0, 0, 0.516846,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.625423,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.405081,-99) , 
0.391833, 1, 3, 0, 0.485735,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.366664,-99) , 
0.665768, 0, 2, 0, 0.458754,-99) , 
118.101, 1, 0, 0, 0.49604,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0628873);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.681273,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.404451,-99) , 
0.578795, 0, 6, 0, 0.56413,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.524066,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.465511,-99) , 
3.02651, 1, 5, 0, 0.487553,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.341673,-99) , 
202.426, 1, 0, 0, 0.477068,-99) , 
210.083, 0, 4, 0, 0.48738,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0771437);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.794757, 1, -1, 1, 0.554505,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.609358,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.456147,-99) , 
3.00074, 1, 5, 0, 0.480104,-99) , 
0.664052, 0, 3, 0, 0.503139,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.562025,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.391211,-99) , 
139.284, 1, 1, 0, 0.477413,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.300577,-99) , 
116.176, 0, 1, 0, 0.418808,-99) , 
2.89834, 0, 5, 0, 0.491239,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0798289);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.647069,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.547868,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.443925,-99) , 
3.08923, 0, 5, 0, 0.499523,-99) , 
3.00669, 1, 5, 0, 0.510984,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.537519,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.418877,-99) , 
0.895553, 0, 2, 0, 0.48338,-99) , 
NN(
0, 
0, 
0.992082, 0, -1, -1, 0.312155,-99) , 
0.831995, 1, 3, 0, 0.441343,-99) , 
2.9794, 0, 5, 0, 0.494828,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0793296);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.754183,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.403309,-99) , 
92.4557, 0, 0, 0, 0.585681,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.594355,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.475526,-99) , 
210.15, 0, 4, 0, 0.490959,-99) , 
0.35823, 1, 6, 0, 0.50819,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.547344,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.435486,-99) , 
89.9925, 1, 0, 0, 0.481553,-99) , 
NN(
0, 
0, 
0.992082, 0, -1, -1, 0.329547,-99) , 
0.831995, 1, 3, 0, 0.444529,-99) , 
2.9794, 0, 5, 0, 0.493449,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0513719);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.642526,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.623479,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.495344,-99) , 
3.1303, 0, 5, 0, 0.509874,-99) , 
3.00669, 1, 5, 0, 0.520148,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.545836,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.375638,-99) , 
119.604, 0, 1, 0, 0.487273,-99) , 
NN(
0, 
0, 
0.989822, 0, -1, -1, 0.354017,-99) , 
0.789999, 1, 3, 0, 0.451676,-99) , 
2.9794, 0, 5, 0, 0.504316,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0704361);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.889071, 1, -1, 1, 0.546616,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.551762,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.403695,-99) , 
0.750516, 0, 2, 0, 0.474307,-99) , 
0.307108, 0, 3, 0, 0.528352,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.570417,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.453146,-99) , 
0.537552, 0, 3, 0, 0.481467,-99) , 
NN(
0, 
0, 
0.992082, 0, -1, -1, 0.35904,-99) , 
0.831995, 1, 3, 0, 0.451943,-99) , 
2.9794, 0, 5, 0, 0.510731,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0437644);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.664052, 0, -1, 1, 0.522362,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.432501,-99) , 
63.7243, 0, 0, 0, 0.512392,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.546782,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.411877,-99) , 
0.96137, 1, 2, 0, 0.48969,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.329792,-99) , 
124.611, 1, 0, 0, 0.447545,-99) , 
2.89834, 0, 5, 0, 0.503353,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0406809);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.167655, 1, -1, 1, 0.523919,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.505471,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.278794,-99) , 
172.233, 1, 1, 0, 0.469426,-99) , 
93.8793, 0, 0, 0, 0.502544,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.422925,-99) , 
202.426, 1, 0, 0, 0.496251,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0765489);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.721405,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.494374,-99) , 
0.958221, 0, 2, 0, 0.536119,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.399104,-99) , 
0.916019, 1, 3, 0, 0.515585,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.605364,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.464543,-99) , 
128.826, 1, 4, 0, 0.527524,-99) , 
NN(
0, 
0, 
79.2989, 0, -1, -1, 0.427325,-99) , 
126.19, 0, 1, 0, 0.470719,-99) , 
147.184, 0, 4, 0, 0.488842,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0575572);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.958221, 0, -1, 1, 0.548381,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.417596,-99) , 
0.916019, 1, 3, 0, 0.528852,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.517211,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.387994,-99) , 
105.249, 0, 4, 0, 0.502435,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.354988,-99) , 
0.628234, 0, 2, 0, 0.482342,-99) , 
147.184, 0, 4, 0, 0.501144,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0685919);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.655953,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.469455,-99) , 
0.657016, 0, 6, 0, 0.551431,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.458971,-99) , 
1.07574, 1, 6, 0, 0.51882,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.574128,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.473463,-99) , 
0.856052, 1, 2, 0, 0.491325,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.368274,-99) , 
0.628234, 0, 2, 0, 0.474655,-99) , 
147.184, 0, 4, 0, 0.492503,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0605408);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.544423,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.478222,-99) , 
92.9845, 0, 0, 0, 0.516495,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.560171,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.295411,-99) , 
3.04866, 0, 5, 0, 0.459049,-99) , 
146.209, 1, 0, 0, 0.507048,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.399496,-99) , 
2.65518, 0, 5, 0, 0.502579,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0734698);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.640285,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.395752,-99) , 
0.876568, 0, 2, 0, 0.545215,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.517795,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.364992,-99) , 
3.05556, 0, 5, 0, 0.496331,-99) , 
3.0268, 1, 5, 0, 0.508443,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.558646,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.443341,-99) , 
124.262, 0, 1, 0, 0.494186,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.339566,-99) , 
124.611, 1, 0, 0, 0.453173,-99) , 
2.89834, 0, 5, 0, 0.500753,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0586626);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.588968,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.512066,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.349641,-99) , 
187.786, 1, 1, 0, 0.491753,-99) , 
108.69, 0, 0, 0, 0.506567,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.543191,-99) , 
NN(
0, 
0, 
0.985642, 1, -1, -1, 0.4174,-99) , 
1.61384, 0, 6, 0, 0.466265,-99) , 
118.101, 1, 0, 0, 0.492197,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0689799);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.625068,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.452449,-99) , 
192.952, 1, 1, 0, 0.544209,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.452075,-99) , 
1.07574, 1, 6, 0, 0.511436,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.513492,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.436041,-99) , 
117.504, 0, 1, 0, 0.484595,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.368284,-99) , 
0.628234, 0, 2, 0, 0.468774,-99) , 
147.184, 0, 4, 0, 0.485889,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0852648);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.683172,-99) , 
NN(
0, 
0, 
0.988404, 0, -1, -1, 0.390038,-99) , 
0.916442, 1, 2, 0, 0.541933,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.641199,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.433442,-99) , 
89.0265, 0, 0, 0, 0.564381,-99) , 
NN(
0, 
0, 
0.80387, 1, -1, -1, 0.457782,-99) , 
0.895008, 0, 3, 0, 0.475444,-99) , 
194.358, 0, 4, 0, 0.487158,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0697377);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.599302,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.5342,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.332184,-99) , 
0.916019, 1, 3, 0, 0.503366,-99) , 
146.792, 1, 1, 0, 0.526643,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.603964,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.469634,-99) , 
0.853012, 0, 3, 0, 0.496064,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.381083,-99) , 
105.249, 0, 4, 0, 0.483734,-99) , 
147.184, 0, 4, 0, 0.500912,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0664797);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.679174,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.513557,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.409279,-99) , 
0.550114, 1, 3, 0, 0.497369,-99) , 
0.668106, 0, 3, 0, 0.513491,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.569419,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.377946,-99) , 
152.866, 1, 1, 0, 0.509965,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.342835,-99) , 
0.874204, 0, 3, 0, 0.468768,-99) , 
0.811015, 1, 3, 0, 0.502337,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0482184);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.621128,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.426183,-99) , 
0.287223, 0, 3, 0, 0.545661,-99) , 
NN(
0, 
0, 
142.847, 1, -1, -1, 0.483444,-99) , 
0.770216, 1, 2, 0, 0.498587,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.429973,-99) , 
202.426, 1, 0, 0, 0.493208,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0435813);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.770567, 1, -1, 1, 0.522909,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.536971,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.358194,-99) , 
212.391, 0, 4, 0, 0.447307,-99) , 
176.995, 1, 1, 0, 0.509038,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.45659,-99) , 
0.540432, 0, 2, 0, 0.50195,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0419234);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.609981,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.442112,-99) , 
0.287223, 0, 3, 0, 0.544818,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.500425,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.32557,-99) , 
142.847, 1, 0, 0, 0.486593,-99) , 
0.770216, 1, 2, 0, 0.500698,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.436933,-99) , 
202.426, 1, 0, 0, 0.495728,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0435639);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.542943,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.515772,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.455407,-99) , 
0.869257, 1, 6, 0, 0.491023,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.330668,-99) , 
162.02, 1, 0, 0, 0.482311,-99) , 
1.74671, 0, 6, 0, 0.489843,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0423627);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.564542,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.483623,-99) , 
3.00152, 1, 5, 0, 0.496995,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.545501,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.351814,-99) , 
2.7754, 1, 5, 0, 0.433483,-99) , 
2.88949, 0, 5, 0, 0.490108,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.378616,-99) , 
2.57413, 0, 5, 0, 0.487365,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0662761);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.723368,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.422885,-99) , 
92.4557, 0, 0, 0, 0.578616,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.51269,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.417181,-99) , 
0.687261, 0, 6, 0, 0.488954,-99) , 
0.35823, 1, 6, 0, 0.504928,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.525787,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.443743,-99) , 
0.874663, 0, 2, 0, 0.491646,-99) , 
NN(
0, 
0, 
0.992082, 0, -1, -1, 0.352911,-99) , 
0.831995, 1, 3, 0, 0.457867,-99) , 
2.9794, 0, 5, 0, 0.493958,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.062321);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.878203, 1, -1, 1, 0.580077,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.423359,-99) , 
0.578795, 0, 6, 0, 0.523067,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.627308,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.477473,-99) , 
147.223, 0, 4, 0, 0.49405,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.393032,-99) , 
156.74, 1, 4, 0, 0.479797,-99) , 
178.634, 0, 4, 0, 0.489034,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0294612);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.569257,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.495603,-99) , 
0.708935, 1, 2, 0, 0.509421,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.422838,-99) , 
162.02, 1, 0, 0, 0.50275,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.422563,-99) , 
2.28413, 1, 6, 0, 0.498044,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0413778);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.537248,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.482187,-99) , 
94.0345, 0, 0, 0, 0.514029,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.430043,-99) , 
162.02, 1, 0, 0, 0.507569,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.429768,-99) , 
2.28413, 1, 6, 0, 0.50301,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0615648);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.745911,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.530615,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.427279,-99) , 
76.5238, 0, 0, 0, 0.497807,-99) , 
0.715677, 0, 6, 0, 0.522389,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.561944,-99) , 
NN(
0, 
0, 
123.228, 1, -1, -1, 0.465912,-99) , 
1.81407, 0, 6, 0, 0.486062,-99) , 
0.806215, 1, 6, 0, 0.502962,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.035271);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
123.438, 1, -1, 1, 0.546933,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.513514,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.398715,-99) , 
133.521, 1, 0, 0, 0.502567,-99) , 
1.33825, 0, 6, 0, 0.510567,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.436148,-99) , 
2.01542, 1, 6, 0, 0.504689,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0399963);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.528032,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.469545,-99) , 
146.197, 1, 1, 0, 0.507738,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.440743,-99) , 
162.02, 1, 0, 0, 0.502598,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.433468,-99) , 
2.28413, 1, 6, 0, 0.498533,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0584652);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.702198,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.461094,-99) , 
92.4557, 0, 0, 0, 0.585616,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.508117,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.430176,-99) , 
0.687261, 0, 6, 0, 0.488787,-99) , 
0.35823, 1, 6, 0, 0.505857,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.567612,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.454522,-99) , 
89.9925, 1, 0, 0, 0.502534,-99) , 
NN(
0, 
0, 
0.989822, 0, -1, -1, 0.37618,-99) , 
0.789999, 1, 3, 0, 0.468735,-99) , 
2.9794, 0, 5, 0, 0.49718,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0759322);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.649881,-99) , 
NN(
0, 
0, 
225.777, 1, -1, -1, 0.419158,-99) , 
0.895553, 1, 2, 0, 0.528131,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.693507,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.475719,-99) , 
147.032, 0, 4, 0, 0.522985,-99) , 
NN(
0, 
0, 
157.509, 1, -1, -1, 0.45496,-99) , 
0.937629, 0, 2, 0, 0.48661,-99) , 
194.358, 0, 4, 0, 0.49374,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0287321);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.54887,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.497131,-99) , 
3.02651, 1, 5, 0, 0.515655,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.449632,-99) , 
162.02, 1, 0, 0, 0.510599,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.440599,-99) , 
2.28413, 1, 6, 0, 0.506494,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0259024);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.708935, 1, -1, 1, 0.517705,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.456752,-99) , 
162.02, 1, 0, 0, 0.513041,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.447693,-99) , 
2.28413, 1, 6, 0, 0.509212,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0397794);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.54682,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.518384,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.405712,-99) , 
133.521, 1, 0, 0, 0.507793,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.423836,-99) , 
1.44871, 1, 6, 0, 0.498439,-99) , 
1.74671, 0, 6, 0, 0.504431,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0618762);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.693438,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.472498,-99) , 
92.4557, 0, 0, 0, 0.586232,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.539743,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.466538,-99) , 
0.664052, 0, 3, 0, 0.489412,-99) , 
0.35823, 1, 6, 0, 0.506427,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.530072,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.447732,-99) , 
2.82624, 0, 5, 0, 0.500033,-99) , 
NN(
0, 
0, 
0.992082, 0, -1, -1, 0.37563,-99) , 
0.831995, 1, 3, 0, 0.469934,-99) , 
2.9794, 0, 5, 0, 0.497881,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.062107);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.710013,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.512551,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.431662,-99) , 
0.536584, 1, 3, 0, 0.497697,-99) , 
0.683091, 0, 3, 0, 0.512955,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.563608,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.39316,-99) , 
152.866, 1, 1, 0, 0.511748,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.355644,-99) , 
0.871824, 0, 3, 0, 0.469423,-99) , 
0.790017, 1, 3, 0, 0.50162,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0480331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.675978,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.479594,-99) , 
92.4557, 0, 0, 0, 0.579744,-99) , 
NN(
0, 
0, 
0.93701, 1, -1, -1, 0.488049,-99) , 
0.35823, 1, 6, 0, 0.504063,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.547797,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.38225,-99) , 
2.74969, 0, 5, 0, 0.501244,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.397015,-99) , 
0.540959, 0, 6, 0, 0.461161,-99) , 
2.9794, 0, 5, 0, 0.493977,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0566533);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.628646,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.528177,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.459071,-99) , 
0.0277778, 1, 7, 0, 0.504083,-99) , 
3.00669, 1, 5, 0, 0.513949,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.535874,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.393654,-99) , 
2.74969, 0, 5, 0, 0.495978,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.408569,-99) , 
0.540959, 0, 6, 0, 0.462398,-99) , 
2.9794, 0, 5, 0, 0.501853,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.041227);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.615326,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.583027,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.489328,-99) , 
3.1303, 0, 5, 0, 0.499796,-99) , 
3.00669, 1, 5, 0, 0.508901,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.564723,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.461771,-99) , 
0.537552, 0, 3, 0, 0.48704,-99) , 
NN(
0, 
0, 
0.992082, 0, -1, -1, 0.391126,-99) , 
0.831995, 1, 3, 0, 0.463868,-99) , 
2.9794, 0, 5, 0, 0.498348,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0927805);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.566928,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.47936,-99) , 
149.241, 1, 4, 0, 0.531919,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.610095,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.268927,-99) , 
148.108, 0, 4, 0, 0.444371,-99) , 
3.12353, 1, 5, 0, 0.515478,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.60032,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.40671,-99) , 
135.17, 1, 4, 0, 0.495969,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.407874,-99) , 
116.176, 0, 1, 0, 0.470263,-99) , 
2.9794, 0, 5, 0, 0.504893,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0536167);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.645416,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.517679,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.406936,-99) , 
103.651, 0, 0, 0, 0.461637,-99) , 
0.895553, 1, 2, 0, 0.549817,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.595219,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.486348,-99) , 
0.895008, 0, 3, 0, 0.503403,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.385746,-99) , 
105.234, 0, 4, 0, 0.494242,-99) , 
194.358, 0, 4, 0, 0.503819,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.056229);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.708764,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.559528,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.488787,-99) , 
0.958221, 0, 2, 0, 0.506355,-99) , 
0.683091, 0, 3, 0, 0.521024,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.599411,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.461106,-99) , 
0.932459, 1, 3, 0, 0.514756,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.388743,-99) , 
0.871824, 0, 3, 0, 0.480945,-99) , 
0.790017, 1, 3, 0, 0.510638,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0620208);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.693685,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.525472,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.412083,-99) , 
0.635642, 1, 3, 0, 0.515666,-99) , 
0.730927, 0, 3, 0, 0.526418,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.63875,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.575956,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.423644,-99) , 
157.864, 0, 4, 0, 0.463716,-99) , 
0.225997, 1, 6, 0, 0.485916,-99) , 
0.811015, 1, 3, 0, 0.516361,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0451685);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.688144, 1, -1, 1, 0.536272,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.5758,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.474354,-99) , 
1.28249, 0, 6, 0, 0.497032,-99) , 
147.184, 0, 4, 0, 0.512564,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.451436,-99) , 
2.01542, 1, 6, 0, 0.507733,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0732657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.718244,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.531207,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.415305,-99) , 
0.840774, 0, 3, 0, 0.488395,-99) , 
0.90776, 1, 2, 0, 0.526934,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.571167,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.514607,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.424115,-99) , 
3.06045, 0, 5, 0, 0.474033,-99) , 
0.958221, 0, 2, 0, 0.495207,-99) , 
0.559035, 0, 3, 0, 0.507996,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0622057);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.732043,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.515772,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.403437,-99) , 
192.519, 1, 1, 0, 0.494539,-99) , 
0.715677, 0, 6, 0, 0.51793,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.564525,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.473716,-99) , 
3.06045, 1, 5, 0, 0.508664,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.397837,-99) , 
112.633, 0, 1, 0, 0.488092,-99) , 
0.806215, 1, 6, 0, 0.501898,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0334185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.540697,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.512259,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.420267,-99) , 
125.861, 1, 0, 0, 0.501454,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.371667,-99) , 
162.02, 1, 0, 0, 0.494498,-99) , 
1.74671, 0, 6, 0, 0.500274,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0555008);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.572412,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.49524,-99) , 
192.287, 0, 4, 0, 0.51202,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.556037,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.310134,-99) , 
0.992443, 0, 2, 0, 0.435637,-99) , 
0.916019, 1, 3, 0, 0.501901,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.630774,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.437374,-99) , 
121.464, 0, 1, 0, 0.507929,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.380771,-99) , 
0.328053, 0, 3, 0, 0.464124,-99) , 
115.734, 0, 4, 0, 0.494323,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0476867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.657934,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.508604,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.445046,-99) , 
115.734, 0, 4, 0, 0.495872,-99) , 
0.668106, 0, 3, 0, 0.510499,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.596915,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.521168,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.405539,-99) , 
0.979496, 0, 6, 0, 0.454676,-99) , 
0.225997, 1, 6, 0, 0.472693,-99) , 
0.811015, 1, 3, 0, 0.501184,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0419272);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.638051,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.498164,-99) , 
0.770567, 1, 2, 0, 0.516708,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.397572,-99) , 
0.540432, 0, 2, 0, 0.503881,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.52177,-99) , 
NN(
0, 
0, 
109.762, 0, -1, -1, 0.405982,-99) , 
0.89883, 1, 2, 0, 0.46339,-99) , 
176.995, 1, 1, 0, 0.49548,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0427733);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.770567, 1, -1, 1, 0.52443,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.407656,-99) , 
0.540432, 0, 2, 0, 0.511896,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.511301,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.505499,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.340928,-99) , 
109.762, 0, 0, 0, 0.416132,-99) , 
0.89883, 1, 2, 0, 0.463389,-99) , 
176.995, 1, 1, 0, 0.501842,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0436849);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.686658, 1, -1, 1, 0.529835,-99) , 
NN(
0, 
0, 
0.328053, 0, -1, -1, 0.456226,-99) , 
123.781, 0, 4, 0, 0.503504,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.500609,-99) , 
NN(
0, 
0, 
109.762, 0, -1, -1, 0.416735,-99) , 
0.89883, 1, 2, 0, 0.458453,-99) , 
176.995, 1, 1, 0, 0.494173,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0381413);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.61659,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.494781,-99) , 
0.770567, 1, 2, 0, 0.510815,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.412959,-99) , 
0.540432, 0, 2, 0, 0.500397,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.50106,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.513467,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.324977,-99) , 
3.08362, 1, 5, 0, 0.420477,-99) , 
228.036, 0, 4, 0, 0.458434,-99) , 
176.995, 1, 1, 0, 0.491708,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0458346);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0.770567, 1, -1, 1, 0.517853,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.422235,-99) , 
0.540432, 0, 2, 0, 0.507697,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.57802,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.371216,-99) , 
102.557, 0, 0, 0, 0.493392,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.415692,-99) , 
0.412154, 0, 3, 0, 0.453788,-99) , 
176.995, 1, 1, 0, 0.496541,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0243654);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.620976,-99) , 
NN(
0, 
0, 
176.072, 1, -1, -1, 0.488858,-99) , 
212.437, 0, 4, 0, 0.495164,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.432907,-99) , 
238.59, 1, 1, 0, 0.490366,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0419174);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.524507,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.460989,-99) , 
1.478, 1, 6, 0, 0.510286,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.372523,-99) , 
2.65518, 0, 5, 0, 0.504724,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, -1, 0.497428,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.51634,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.340351,-99) , 
3.08362, 1, 5, 0, 0.430194,-99) , 
228.036, 0, 4, 0, 0.461998,-99) , 
176.995, 1, 1, 0, 0.495918,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0254443);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.537085,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.503209,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.418564,-99) , 
125.861, 1, 0, 0, 0.493318,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.366925,-99) , 
162.02, 1, 0, 0, 0.486458,-99) , 
1.74671, 0, 6, 0, 0.492833,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0233432);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.530753,-99) , 
NN(
0, 
0, 
162.02, 1, -1, -1, 0.482186,-99) , 
1.74671, 0, 6, 0, 0.488298,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0440847);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.586079,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.478635,-99) , 
0.959595, 0, 2, 0, 0.516018,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.503919,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.296518,-99) , 
187.786, 1, 1, 0, 0.480449,-99) , 
105.023, 0, 0, 0, 0.496727,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.428202,-99) , 
2.28413, 1, 6, 0, 0.492661,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0358102);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.531471,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.513248,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.460986,-99) , 
93.985, 0, 0, 0, 0.49027,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.382485,-99) , 
162.02, 1, 0, 0, 0.484482,-99) , 
1.74671, 0, 6, 0, 0.490394,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0349116);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.597007,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.489427,-99) , 
192.413, 0, 1, 0, 0.512428,-99) , 
NN(
0, 
0, 
187.786, 1, -1, -1, 0.475673,-99) , 
105.023, 0, 0, 0, 0.492482,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.430229,-99) , 
2.28413, 1, 6, 0, 0.488782,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0367504);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.580272,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.478666,-99) , 
122.454, 0, 0, 0, 0.532917,-99) , 
NN(
NN(
0, 
0, 
0, 1, -1, 1, 0.510384,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.454327,-99) , 
0.850385, 1, 6, 0, 0.491055,-99) , 
1.332, 0, 6, 0, 0.499501,-99) , 
NN(
0, 
0, 
0, 1, -1, -1, 0.438807,-99) , 
2.28413, 1, 6, 0, 0.4959,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
