/**
    @file hbb.h

    @brief This file is automatically generated from ROOT file /tmp/wilken/ZH_Summer11.root
    on Wed Oct 19 19:22:33 UTC 2011 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed Oct 19 19:22:33 UTC 2011

    $Id: hbb.h,v 1.4 2010/09/29 15:12:50 haryo Exp $
 */


#ifndef hbb_hbb_h
#define hbb_hbb_h


#include<Rtypes.h>


/**
    @class hbb

    @brief A class to hold the leaves/variables of a hbb.
    This class is automatically generated from ROOT file /tmp/wilken/ZH_Summer11.root
    on Wed Oct 19 19:22:33 UTC 2011 by the script createReader.py.
    Users may need to edit the content of this class to fit their needs.

    @date Wed Oct 19 19:22:33 UTC 2011

    $Id: hbb.h,v 1.4 2010/09/29 15:12:50 haryo Exp $
 */
class hbb
{

public:

    /**
        Default constructor.
     */
    hbb();

    /**
        Destructor.
     */
    ~hbb();

    // The leaves/variables of hbb
    Int_t           nEvents;
    Int_t           evtNumber;
    Int_t           runNumber;
    Int_t           lumiBlock;
    Bool_t          hasGoodPV;
    Int_t           SMTtags;
    Bool_t          HLT_IsoMu13_v4_trig;
    Bool_t          HLT_IsoMu15_v4_trig;
    Bool_t          HLT_IsoMu17_v4_trig;
    Bool_t          HLT_IsoMu17_v5_trig;
    Bool_t          HLT_IsoMu17_v6_trig;
    Bool_t          HLT_IsoMu17_v7_trig;
    Bool_t          HLT_IsoMu17_v8_trig;
    Bool_t          HLT_CentralJet80_MET80_trig;
    Bool_t          HLT_pfMHT150_trig;
    Bool_t          HLT_L1_ETM30_trig;
    Bool_t          HLT_MET100_trig;
    Int_t           nJets;
    Int_t           nMuons;
    Int_t           nRawJets;
    Int_t           nRawMuons;
    Double_t        jetPt[9];
    Double_t        jetEta[9];
    Double_t        jetPhi[9];
    Double_t        jetPx[9];
    Double_t        jetPy[9];
    Double_t        jetPz[9];
    Double_t        jetP[9];
    Int_t           jetFlavour[9];
    Int_t           jetNumberOfDaughters[9];
    Int_t           jetChargedMultiplicity[9];
    Double_t        jetChargedEmEnergyFraction[9];
    Double_t        jetNeutralHadronEnergyFraction[9];
    Double_t        jetNeutralEmEnergyFraction[9];
    Double_t        jetChargedHadronEnergyFraction[9];
    Double_t        muonPt[3];
    Double_t        muonEta[3];
    Double_t        muonPhi[3];
    Double_t        muonP[3];
    Double_t        muonPx[3];
    Double_t        muonPy[3];
    Double_t        muonPz[3];
    Bool_t          isGlobalMuon[3];
    Bool_t          isTrackerMuon[3];
    Double_t        muonNormalizedChi2[3];
    Double_t        muonDB[3];
    Double_t        muonTrackIso[3];
    Double_t        muonCaloIso[3];
    Int_t           muonNumberOfValidTrackerHits[3];
    Int_t           muonNumberOfValidPixelHits[3];
    Int_t           muonNumberOfValidMuonHits[3];
    Int_t           muonNumberOfMatches[3];
    Bool_t          SMTevent;
    Double_t        bDisc_TCHE[9];
    Double_t        bDisc_TCHP[9];
    Double_t        bDisc_SSVHE[9];
    Double_t        bDisc_SSVHP[9];
    Double_t        bDisc_CSV[9];
    Double_t        bDisc_JP[9];
    Double_t        bDisc_JBP[9];
    Double_t        bDisc_SMT[9];
    Double_t        bDisc_SMTIP3dB[9];
    Double_t        bDisc_SMTPt[9];
    Double_t        bDisc_SETIP3dB[9];
    Double_t        bDisc_SETPt[9];
    Double_t        bDisc_CSVMVA[9];
    Bool_t          smt_jet[9];
    Double_t        MetPFSumEt;
    Double_t        MetPFmEtSig;
    Double_t        MetPFPx;
    Double_t        MetPFPy;
    Double_t        MetPFPz;
    Double_t        MetPFPt;
    Double_t        MetPFPhi;
    Double_t        MetPFEta;
    Bool_t          muIsPVcompatible[3];
    Double_t        dR_isoMu_jet[9][100];
    Int_t           MCHstatus;
    Int_t           MCHmomid;
    Int_t           MCHGmomid;
    Double_t        MCHpt;
    Double_t        MCHeta;
    Double_t        MCHphi;
    Double_t        MCHmass;
    Int_t           MCHndau;
    Int_t           MCHdauid[2];
    Double_t        MCHdaupt[2];
    Double_t        MCHdaueta[2];
    Double_t        MCHdauphi[2];
    Int_t           MCZstatus;
    Int_t           MCZmomid;
    Int_t           MCZGmomid;
    Int_t           MCZcharge;
    Double_t        MCZpt;
    Double_t        MCZeta;
    Double_t        MCZphi;
    Double_t        MCZmass;
    Int_t           MCZndau;
    Int_t           MCZdauid[8];
    Double_t        MCZdaupt[8];
    Double_t        MCZdaueta[8];
    Double_t        MCZdauphi[8];
    Int_t           MCbstatus;
    Int_t           MCbmomid;
    Int_t           MCbGmomid;
    Double_t        MCbpt;
    Double_t        MCbeta;
    Double_t        MCbphi;
    Double_t        MCbpx;
    Double_t        MCbpy;
    Double_t        MCbpz;
    Double_t        MCbE;
    Int_t           MCbbarstatus;
    Int_t           MCbbarmomid;
    Int_t           MCbbarGmomid;
    Double_t        MCbbarpt;
    Double_t        MCbbareta;
    Double_t        MCbbarphi;
    Double_t        MCbbarpx;
    Double_t        MCbbarpy;
    Double_t        MCbbarpz;
    Double_t        MCbbarE;
    Int_t           MCHDaubNdau;
    Double_t        MCHDaubdaupt[1];
    Double_t        MCHDaubdaueta[1];
    Double_t        MCHDaubdauphi[1];
    Double_t        MCHDaubdaupx[1];
    Double_t        MCHDaubdaupy[1];
    Double_t        MCHDaubdaupz[1];
    Double_t        MCHDaubdauE[1];
    Int_t           MCHDaubbarNdau;
    Double_t        MCHDaubbardaupt[1];
    Double_t        MCHDaubbardaueta[1];
    Double_t        MCHDaubbardauphi[1];
    Double_t        MCHDaubbardaupx[1];
    Double_t        MCHDaubbardaupy[1];
    Double_t        MCHDaubbardaupz[1];
    Double_t        MCHDaubbardauE[1];
    Int_t           MCccstatus;
    Int_t           MCccmomid;
    Int_t           MCccGmomid;

};

#endif
