/**
    @file tautree.h

    @brief This file is automatically generated from ROOT file /home/hep/wilken/taus/testedm21/src/VHbbAnalysis/VHbbDataFormats/bin/TTJetsV21emu3.root
    on Wed May 16 16:08:42 UTC 2012 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed May 16 16:08:42 UTC 2012

    $Id: tautree.h,v 1.4 2010/09/29 15:12:50 haryo Exp $
 */


#ifndef tautree_tautree_h
#define tautree_tautree_h


#include<Rtypes.h>


/**
    @class tautree

    @brief A class to hold the leaves/variables of a tautree.
    This class is automatically generated from ROOT file /home/hep/wilken/taus/testedm21/src/VHbbAnalysis/VHbbDataFormats/bin/TTJetsV21emu3.root
    on Wed May 16 16:08:42 UTC 2012 by the script createReader.py.
    Users may need to edit the content of this class to fit their needs.

    @date Wed May 16 16:08:42 UTC 2012

    $Id: tautree.h,v 1.4 2010/09/29 15:12:50 haryo Exp $
 */
class tautree
{

public:

    /**
        Default constructor.
     */
    tautree();

    /**
        Destructor.
     */
    ~tautree();

    // The leaves/variables of tautree
    Float_t         H_mass;
    Float_t         H_pt;
    Float_t         H_eta;
    Float_t         H_phi;
    Float_t         H_dR;
    Float_t         H_dPhi;
    Float_t         H_dEta;
    Float_t         V_mass;
    Float_t         V_pt;
    Float_t         V_eta;
    Float_t         V_phi;
    Int_t           FatH_FatHiggsFlag;
    Float_t         FatH_mass;
    Float_t         FatH_pt;
    Float_t         FatH_eta;
    Float_t         FatH_phi;
    Float_t         FatH_filteredmass;
    Float_t         FatH_filteredpt;
    Float_t         genZ_mass;
    Float_t         genZ_pt;
    Float_t         genZ_eta;
    Float_t         genZ_phi;
    Float_t         genZ_status;
    Float_t         genZ_charge;
    Float_t         genZ_momid;
    Float_t         genZstar_mass;
    Float_t         genZstar_pt;
    Float_t         genZstar_eta;
    Float_t         genZstar_phi;
    Float_t         genZstar_status;
    Float_t         genZstar_charge;
    Float_t         genZstar_momid;
    Float_t         genW_mass;
    Float_t         genW_pt;
    Float_t         genW_eta;
    Float_t         genW_phi;
    Float_t         genW_status;
    Float_t         genW_charge;
    Float_t         genW_momid;
    Float_t         genWstar_mass;
    Float_t         genWstar_pt;
    Float_t         genWstar_eta;
    Float_t         genWstar_phi;
    Float_t         genWstar_status;
    Float_t         genWstar_charge;
    Float_t         genWstar_momid;
    Float_t         genH_mass;
    Float_t         genH_pt;
    Float_t         genH_eta;
    Float_t         genH_phi;
    Float_t         genH_status;
    Float_t         genH_charge;
    Float_t         genH_momid;
    Float_t         genB_mass;
    Float_t         genB_pt;
    Float_t         genB_eta;
    Float_t         genB_phi;
    Float_t         genB_status;
    Float_t         genB_charge;
    Float_t         genB_momid;
    Float_t         genBbar_mass;
    Float_t         genBbar_pt;
    Float_t         genBbar_eta;
    Float_t         genBbar_phi;
    Float_t         genBbar_status;
    Float_t         genBbar_charge;
    Float_t         genBbar_momid;
    Float_t         genTop_bmass;
    Float_t         genTop_bpt;
    Float_t         genTop_beta;
    Float_t         genTop_bphi;
    Float_t         genTop_bstatus;
    Float_t         genTop_wdau1mass;
    Float_t         genTop_wdau1pt;
    Float_t         genTop_wdau1eta;
    Float_t         genTop_wdau1phi;
    Float_t         genTop_wdau1id;
    Float_t         genTop_wdau2mass;
    Float_t         genTop_wdau2pt;
    Float_t         genTop_wdau2eta;
    Float_t         genTop_wdau2phi;
    Float_t         genTop_wdau2id;
    Float_t         genTbar_bmass;
    Float_t         genTbar_bpt;
    Float_t         genTbar_beta;
    Float_t         genTbar_bphi;
    Float_t         genTbar_bstatus;
    Float_t         genTbar_wdau1mass;
    Float_t         genTbar_wdau1pt;
    Float_t         genTbar_wdau1eta;
    Float_t         genTbar_wdau1phi;
    Float_t         genTbar_wdau1id;
    Float_t         genTbar_wdau2mass;
    Float_t         genTbar_wdau2pt;
    Float_t         genTbar_wdau2eta;
    Float_t         genTbar_wdau2phi;
    Float_t         genTbar_wdau2id;
    UChar_t         TkSharing_HiggsCSVtkSharing;
    UChar_t         TkSharing_HiggsIPtkSharing;
    UChar_t         TkSharing_HiggsSVtkSharing;
    UChar_t         TkSharing_FatHiggsCSVtkSharing;
    UChar_t         TkSharing_FatHiggsIPtkSharing;
    UChar_t         TkSharing_FatHiggsSVtkSharing;
    Int_t           nhJets;
    Int_t           nfathFilterJets;
    Int_t           naJets;
    Float_t         hJet_pt[2];
    Float_t         hJet_eta[2];
    Float_t         hJet_phi[2];
    Float_t         hJet_e[2];
    Float_t         hJet_csv[2];
    Float_t         hJet_csvivf[2];
    Float_t         hJet_cmva[2];
    Float_t         hJet_cosTheta[2];
    Int_t           hJet_numTracksSV[2];
    Float_t         hJet_chf[2];
    Float_t         hJet_nhf[2];
    Float_t         hJet_cef[2];
    Float_t         hJet_nef[2];
    Float_t         hJet_nch[2];
    Float_t         hJet_nconstituents[2];
    Float_t         hJet_flavour[2];
    Int_t           hJet_isSemiLept[2];
    Int_t           hJet_isSemiLeptMCtruth[2];
    Int_t           hJet_SoftLeptpdgId[2];
    Int_t           hJet_SoftLeptIdlooseMu[2];
    Int_t           hJet_SoftLeptId95[2];
    Float_t         hJet_SoftLeptPt[2];
    Float_t         hJet_SoftLeptdR[2];
    Float_t         hJet_SoftLeptptRel[2];
    Float_t         hJet_SoftLeptRelCombIso[2];
    Float_t         hJet_genPt[2];
    Float_t         hJet_genEta[2];
    Float_t         hJet_genPhi[2];
    Float_t         hJet_JECUnc[2];
    Float_t         hJet_vtxMass[2];
    Float_t         hJet_vtx3dL[2];
    Float_t         hJet_vtx3deL[2];
    UChar_t         hJet_id[2];
    UChar_t         hJet_SF_CSVL[2];
    UChar_t         hJet_SF_CSVM[2];
    UChar_t         hJet_SF_CSVT[2];
    UChar_t         hJet_SF_CSVLerr[2];
    UChar_t         hJet_SF_CSVMerr[2];
    UChar_t         hJet_SF_CSVTerr[2];
    Float_t         fathFilterJets_pt[3];
    Float_t         fathFilterJets_eta[3];
    Float_t         fathFilterJets_phi[3];
    Float_t         fathFilterJets_e[3];
    Float_t         fathFilterJets_csv[3];
    Float_t         fathFilterJets_csvivf[3];
    Float_t         fathFilterJets_cmva[3];
    Float_t         fathFilterJets_flavour[3];
    Float_t         aJet_pt[16];
    Float_t         aJet_eta[16];
    Float_t         aJet_phi[16];
    Float_t         aJet_e[16];
    Float_t         aJet_csv[16];
    Float_t         aJet_csvivf[16];
    Float_t         aJet_cmva[16];
    Float_t         aJet_cosTheta[16];
    Int_t           aJet_numTracksSV[16];
    Float_t         aJet_chf[16];
    Float_t         aJet_nhf[16];
    Float_t         aJet_cef[16];
    Float_t         aJet_nef[16];
    Float_t         aJet_nch[16];
    Float_t         aJet_nconstituents[16];
    Float_t         aJet_flavour[16];
    Int_t           aJet_isSemiLept[16];
    Int_t           aJet_isSemiLeptMCtruth[16];
    Int_t           aJet_SoftLeptpdgId[16];
    Int_t           aJet_SoftLeptIdlooseMu[16];
    Int_t           aJet_SoftLeptId95[16];
    Float_t         aJet_SoftLeptPt[16];
    Float_t         aJet_SoftLeptdR[16];
    Float_t         aJet_SoftLeptptRel[16];
    Float_t         aJet_SoftLeptRelCombIso[16];
    Float_t         aJet_genPt[16];
    Float_t         aJet_genEta[16];
    Float_t         aJet_genPhi[16];
    Float_t         aJet_JECUnc[16];
    Float_t         aJet_vtxMass[16];
    Float_t         aJet_vtx3dL[16];
    Float_t         aJet_vtx3deL[16];
    UChar_t         aJet_id[16];
    UChar_t         aJet_SF_CSVL[16];
    UChar_t         aJet_SF_CSVM[16];
    UChar_t         aJet_SF_CSVT[16];
    UChar_t         aJet_SF_CSVLerr[16];
    UChar_t         aJet_SF_CSVMerr[16];
    UChar_t         aJet_SF_CSVTerr[16];
    Int_t           numJets;
    Int_t           numBJets;
    Float_t         deltaPullAngle;
    Float_t         deltaPullAngle2;
    Float_t         gendrcc;
    Float_t         gendrbb;
    Float_t         genZpt;
    Float_t         genWpt;
    Float_t         genHpt;
    Float_t         weightTrig;
    Float_t         weightTrigMay;
    Float_t         weightTrigV4;
    Float_t         weightTrigMET;
    Float_t         weightTrigOrMu30;
    Float_t         weightEleRecoAndId;
    Float_t         weightEleTrigJetMETPart;
    Float_t         weightEleTrigElePart;
    Float_t         weightEleTrigEleAugPart;
    Float_t         weightTrigMET80;
    Float_t         weightTrigMET100;
    Float_t         weightTrig2CJet20;
    Float_t         weightTrigMET150;
    Float_t         weightTrigMET802CJet;
    Float_t         weightTrigMET1002CJet;
    Float_t         weightTrigMETLP;
    Float_t         deltaPullAngleAK7;
    Float_t         deltaPullAngle2AK7;
    Float_t         PU0;
    Float_t         PUm1;
    Float_t         PUp1;
    Float_t         PUweight;
    Float_t         PUweight2011B;
    Int_t           eventFlav;
    Int_t           Vtype;
    Float_t         HVdPhi;
    Float_t         HVMass;
    Float_t         HMETdPhi;
    Float_t         VMt;
    Float_t         VMte;
    Float_t         VMtmu;
    Int_t           nvlep;
    Int_t           nalep;
    Float_t         vLepton_mass[2];
    Float_t         vLepton_pt[2];
    Float_t         vLepton_eta[2];
    Float_t         vLepton_phi[2];
    Float_t         vLepton_aodCombRelIso[2];
    Float_t         vLepton_pfCombRelIso[2];
    Float_t         vLepton_photonIso[2];
    Float_t         vLepton_neutralHadIso[2];
    Float_t         vLepton_chargedHadIso[2];
    Float_t         vLepton_chargedPUIso[2];
    Float_t         vLepton_particleIso[2];
    Float_t         vLepton_dxy[2];
    Float_t         vLepton_dz[2];
    Int_t           vLepton_type[2];
    Float_t         vLepton_id80[2];
    Float_t         vLepton_id95[2];
    Float_t         vLepton_vbtf[2];
    Float_t         vLepton_id80NoIso[2];
    Float_t         vLepton_genPt[2];
    Float_t         vLepton_genEta[2];
    Float_t         vLepton_genPhi[2];
    Float_t         vLepton_charge[2];
    Float_t         aLepton_mass[4];
    Float_t         aLepton_pt[4];
    Float_t         aLepton_eta[4];
    Float_t         aLepton_phi[4];
    Float_t         aLepton_aodCombRelIso[4];
    Float_t         aLepton_pfCombRelIso[4];
    Float_t         aLepton_photonIso[4];
    Float_t         aLepton_neutralHadIso[4];
    Float_t         aLepton_chargedHadIso[4];
    Float_t         aLepton_chargedPUIso[4];
    Float_t         aLepton_particleIso[4];
    Float_t         aLepton_dxy[4];
    Float_t         aLepton_dz[4];
    Int_t           aLepton_type[4];
    Float_t         aLepton_id80[4];
    Float_t         aLepton_id95[4];
    Float_t         aLepton_vbtf[4];
    Float_t         aLepton_id80NoIso[4];
    Float_t         aLepton_genPt[4];
    Float_t         aLepton_genEta[4];
    Float_t         aLepton_genPhi[4];
    Float_t         aLepton_charge[4];
    Float_t         top_mass;
    Float_t         top_pt;
    Float_t         top_wMass;
    Int_t           WplusMode;
    Int_t           WminusMode;
    Int_t           nSvs;
    Float_t         Sv_massBCand[6];
    Float_t         Sv_massSv[6];
    Float_t         Sv_pt[6];
    Float_t         Sv_eta[6];
    Float_t         Sv_phi[6];
    Float_t         Sv_dist3D[6];
    Float_t         Sv_dist2D[6];
    Float_t         Sv_distSim2D[6];
    Float_t         Sv_distSig3D[6];
    Float_t         Sv_dist3D_norm[6];
    Float_t         SVH_mass;
    Float_t         SVH_pt;
    Float_t         SVH_eta;
    Float_t         SVH_phi;
    Float_t         SVH_dR;
    Float_t         SVH_dPhi;
    Float_t         SVH_dEta;
    Float_t         rho;
    Float_t         rho25;
    Int_t           nPVs;
    Float_t         METnoPU_et;
    Float_t         METnoPU_sumet;
    Float_t         METnoPU_sig;
    Float_t         METnoPU_phi;
    Float_t         METnoPUCh_et;
    Float_t         METnoPUCh_sumet;
    Float_t         METnoPUCh_sig;
    Float_t         METnoPUCh_phi;
    Float_t         MET_et;
    Float_t         MET_sumet;
    Float_t         MET_sig;
    Float_t         MET_phi;
    Float_t         METtype1corr_et;
    Float_t         METtype1corr_sumet;
    Float_t         METtype1corr_sig;
    Float_t         METtype1corr_phi;
    Float_t         METtype1p2corr_et;
    Float_t         METtype1p2corr_sumet;
    Float_t         METtype1p2corr_sig;
    Float_t         METtype1p2corr_phi;
    Float_t         METnoPUtype1corr_et;
    Float_t         METnoPUtype1corr_sumet;
    Float_t         METnoPUtype1corr_sig;
    Float_t         METnoPUtype1corr_phi;
    Float_t         METnoPUtype1p2corr_et;
    Float_t         METnoPUtype1p2corr_sumet;
    Float_t         METnoPUtype1p2corr_sig;
    Float_t         METnoPUtype1p2corr_phi;
    Float_t         metUnc_et[24];
    Float_t         metUnc_phi[24];
    Float_t         metUnc_sumet[24];
    Float_t         fakeMET_et;
    Float_t         fakeMET_sumet;
    Float_t         fakeMET_sig;
    Float_t         fakeMET_phi;
    Float_t         MHT_mht;
    Float_t         MHT_ht;
    Float_t         MHT_sig;
    Float_t         MHT_phi;
    Float_t         minDeltaPhijetMET;
    Float_t         minDeltaPhijetMETZtau;
    Float_t         jetPt_minDeltaPhijetMET;
    UChar_t         triggerFlags[42];
    Int_t           EVENT_run;
    Int_t           EVENT_lumi;
    Int_t           EVENT_event;
    Int_t           EVENT_json;
    UChar_t         hbhe;
    UChar_t         totalKinematics;
    UChar_t         ecalFlag;
    UChar_t         cschaloFlag;
    UChar_t         hcallaserFlag;
    UChar_t         trackingfailureFlag;
    Float_t         btag1TSF;
    Float_t         btag2TSF;
    Float_t         btag1T2CSF;
    Float_t         btag2CSF;
    Float_t         btagA0CSF;
    Float_t         btagA0TSF;
    Float_t         btag1TA1C;

};

#endif
