/**
    @file tree.h

    @brief This file is automatically generated from ROOT file /mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/malbouis/Hbb/HbbNtuples/Nov10Ntuple/Nov10Ntuple_PUFix_Fall11_2011AandB_OK/Updated_DiJetPt_ZH_ZToLL_HToBB_M-115_7TeV-powheg-herwigppProcV1_Fall11.root
    on Wed Dec  7 11:46:23 UTC 2011 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed Dec  7 11:46:23 UTC 2011

    $Id: tree.h,v 1.4 2010/09/29 15:12:50 haryo Exp $
 */


#ifndef tree_tree_h
#define tree_tree_h


#include<Rtypes.h>


/**
    @class tree

    @brief A class to hold the leaves/variables of a tree.
    This class is automatically generated from ROOT file /mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/malbouis/Hbb/HbbNtuples/Nov10Ntuple/Nov10Ntuple_PUFix_Fall11_2011AandB_OK/Updated_DiJetPt_ZH_ZToLL_HToBB_M-115_7TeV-powheg-herwigppProcV1_Fall11.root
    on Wed Dec  7 11:46:23 UTC 2011 by the script createReader.py.
    Users may need to edit the content of this class to fit their needs.

    @date Wed Dec  7 11:46:23 UTC 2011

    $Id: tree.h,v 1.4 2010/09/29 15:12:50 haryo Exp $
 */
class tree
{

public:

    /**
        Default constructor.
     */
    tree();

    /**
        Destructor.
     */
    ~tree();

    // The leaves/variables of tree
    Float_t         H_mass;
    Float_t         H_pt;
    Float_t         H_eta;
    Float_t         H_phi;
    Float_t         H_dR;
    Float_t         H_dPhi;
    Float_t         H_dEta;
    Float_t         V_mass;
    Float_t         V_pt;
    Float_t         V_eta;
    Float_t         V_phi;
    Int_t           nhJets;
    Int_t           naJets;
    Float_t         hJet_pt[2];
    Float_t         hJet_eta[2];
    Float_t         hJet_phi[2];
    Float_t         hJet_e[2];
    Float_t         hJet_csv[2];
    Float_t         hJet_cosTheta[2];
    Int_t           hJet_numTracksSV[2];
    Float_t         hJet_chf[2];
    Float_t         hJet_nhf[2];
    Float_t         hJet_cef[2];
    Float_t         hJet_nef[2];
    Float_t         hJet_nch[2];
    Float_t         hJet_nconstituents[2];
    Float_t         hJet_flavour[2];
    Float_t         hJet_genPt[2];
    Float_t         hJet_genEta[2];
    Float_t         hJet_genPhi[2];
    Float_t         hJet_JECUnc[2];
    Float_t         hJet_vtxMass[2];
    Float_t         hJet_vtx3dL[2];
    Float_t         hJet_vtx3deL[2];
    UChar_t         hJet_id[2];
    UChar_t         hJet_SF_CSVL[2];
    UChar_t         hJet_SF_CSVM[2];
    UChar_t         hJet_SF_CSVT[2];
    UChar_t         hJet_SF_CSVLerr[2];
    UChar_t         hJet_SF_CSVMerr[2];
    UChar_t         hJet_SF_CSVTerr[2];
    Float_t         aJet_pt[32];
    Float_t         aJet_eta[32];
    Float_t         aJet_phi[32];
    Float_t         aJet_e[32];
    Float_t         aJet_csv[32];
    Float_t         aJet_cosTheta[32];
    Int_t           aJet_numTracksSV[32];
    Float_t         aJet_chf[32];
    Float_t         aJet_nhf[32];
    Float_t         aJet_cef[32];
    Float_t         aJet_nef[32];
    Float_t         aJet_nch[32];
    Float_t         aJet_nconstituents[32];
    Float_t         aJet_flavour[32];
    Float_t         aJet_genPt[32];
    Float_t         aJet_genEta[32];
    Float_t         aJet_genPhi[32];
    Float_t         aJet_JECUnc[32];
    Float_t         aJet_vtxMass[32];
    Float_t         aJet_vtx3dL[32];
    Float_t         aJet_vtx3deL[32];
    UChar_t         aJet_id[32];
    UChar_t         aJet_SF_CSVL[32];
    UChar_t         aJet_SF_CSVM[32];
    UChar_t         aJet_SF_CSVT[32];
    UChar_t         aJet_SF_CSVLerr[32];
    UChar_t         aJet_SF_CSVMerr[32];
    UChar_t         aJet_SF_CSVTerr[32];
    Int_t           numJets;
    Int_t           numBJets;
    Float_t         deltaPullAngle;
    Float_t         deltaPullAngle2;
    Float_t         gendrcc;
    Float_t         gendrbb;
    Float_t         genZpt;
    Float_t         genWpt;
    Float_t         weightTrig;
    Float_t         weightTrigMay;
    Float_t         weightTrigV4;
    Float_t         weightTrigMET;
    Float_t         weightTrigOrMu30;
    Float_t         weightEleRecoAndId;
    Float_t         weightEleTrigJetMETPart;
    Float_t         weightEleTrigElePart;
    Float_t         weightEleTrigEleAugPart;
    Float_t         weightTrigMET80;
    Float_t         weightTrigMET100;
    Float_t         weightTrig2CJet20;
    Float_t         weightTrigMET150;
    Float_t         weightTrigMET802CJet;
    Float_t         weightTrigMET1002CJet;
    Float_t         weightTrigMETLP;
    Float_t         deltaPullAngleAK7;
    Float_t         deltaPullAngle2AK7;
    Float_t         PU0;
    Float_t         PUm1;
    Float_t         PUp1;
    Float_t         PUweight;
    Float_t         PUweight2011B;
    Int_t           eventFlav;
    Int_t           Vtype;
    Float_t         HVdPhi;
    Float_t         HVMass;
    Float_t         HMETdPhi;
    Float_t         VMt;
    Int_t           nvlep;
    Int_t           nalep;
    Float_t         vLepton_mass[2];
    Float_t         vLepton_pt[2];
    Float_t         vLepton_eta[2];
    Float_t         vLepton_phi[2];
    Float_t         vLepton_aodCombRelIso[2];
    Float_t         vLepton_pfCombRelIso[2];
    Float_t         vLepton_photonIso[2];
    Float_t         vLepton_neutralHadIso[2];
    Float_t         vLepton_chargedHadIso[2];
    Float_t         vLepton_chargedPUIso[2];
    Float_t         vLepton_particleIso[2];
    Float_t         vLepton_dxy[2];
    Float_t         vLepton_dz[2];
    Int_t           vLepton_type[2];
    Float_t         vLepton_id80[2];
    Float_t         vLepton_id95[2];
    Float_t         vLepton_vbtf[2];
    Float_t         vLepton_id80NoIso[2];
    Float_t         vLepton_genPt[2];
    Float_t         vLepton_genEta[2];
    Float_t         vLepton_genPhi[2];
    Float_t         aLepton_mass[3];
    Float_t         aLepton_pt[3];
    Float_t         aLepton_eta[3];
    Float_t         aLepton_phi[3];
    Float_t         aLepton_aodCombRelIso[3];
    Float_t         aLepton_pfCombRelIso[3];
    Float_t         aLepton_photonIso[3];
    Float_t         aLepton_neutralHadIso[3];
    Float_t         aLepton_chargedHadIso[3];
    Float_t         aLepton_chargedPUIso[3];
    Float_t         aLepton_particleIso[3];
    Float_t         aLepton_dxy[3];
    Float_t         aLepton_dz[3];
    Int_t           aLepton_type[3];
    Float_t         aLepton_id80[3];
    Float_t         aLepton_id95[3];
    Float_t         aLepton_vbtf[3];
    Float_t         aLepton_id80NoIso[3];
    Float_t         aLepton_genPt[3];
    Float_t         aLepton_genEta[3];
    Float_t         aLepton_genPhi[3];
    Float_t         top_mass;
    Float_t         top_pt;
    Float_t         top_wMass;
    Int_t           WplusMode;
    Int_t           WminusMode;
    Int_t           nSvs;
    Float_t         Sv_massBCand[4];
    Float_t         Sv_massSv[4];
    Float_t         Sv_pt[4];
    Float_t         Sv_eta[4];
    Float_t         Sv_phi[4];
    Float_t         Sv_dist3D[4];
    Float_t         Sv_dist2D[4];
    Float_t         Sv_distSim2D[4];
    Float_t         Sv_distSig3D[4];
    Float_t         Sv_dist3D_norm[4];
    Float_t         SVH_mass;
    Float_t         SVH_pt;
    Float_t         SVH_eta;
    Float_t         SVH_phi;
    Float_t         SVH_dR;
    Float_t         SVH_dPhi;
    Float_t         SVH_dEta;
    Float_t         rho;
    Float_t         rho25;
    Int_t           nPVs;
    Float_t         METnoPU_et;
    Float_t         METnoPU_sumet;
    Float_t         METnoPU_sig;
    Float_t         METnoPU_phi;
    Float_t         METnoPUCh_et;
    Float_t         METnoPUCh_sumet;
    Float_t         METnoPUCh_sig;
    Float_t         METnoPUCh_phi;
    Float_t         MET_et;
    Float_t         MET_sumet;
    Float_t         MET_sig;
    Float_t         MET_phi;
    Float_t         fakeMET_et;
    Float_t         fakeMET_sumet;
    Float_t         fakeMET_sig;
    Float_t         fakeMET_phi;
    Float_t         MHT_mht;
    Float_t         MHT_ht;
    Float_t         MHT_sig;
    Float_t         MHT_phi;
    Float_t         minDeltaPhijetMET;
    Float_t         jetPt_minDeltaPhijetMET;
    UChar_t         triggerFlags[28];
    Int_t           EVENT_run;
    Int_t           EVENT_lumi;
    Int_t           EVENT_event;
    Int_t           EVENT_json;
    UChar_t         hbhe;
    UChar_t         totalKinematics;
    UChar_t         ecalFlag;
    Float_t         btag1TSF;
    Float_t         btag2TSF;
    Float_t         btag1T2CSF;
    Float_t         btag2CSF;
    Float_t         btagA0CSF;
    Float_t         btagA0TSF;
    Float_t         btag1TA1C;

};

#endif
