/**
    @file hbb.cc

    @brief This file is automatically generated from ROOT file /tmp/wilken/ZH_Summer11.root
    on Wed Oct 19 19:22:33 UTC 2011 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed Oct 19 19:22:33 UTC 2011

    $Id: hbb.cc,v 1.3 2010/09/29 15:12:59 haryo Exp $
 */


#include<UserCode/wilken/interface/hbb.h>


hbb::hbb()
{
}


hbb::~hbb()
{
}
