/**
    @file hbbReader.cc

    @brief This file is automatically generated from ROOT file /tmp/wilken/ZH_Summer11.root
    on Wed Oct 19 19:22:33 UTC 2011 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed Oct 19 19:22:33 UTC 2011

    $Id: hbbReader.cc,v 1.5 2010/09/29 15:13:14 haryo Exp $
 */


#include<UserCode/wilken/interface/hbbReader.h>


hbbReader::hbbReader(std::string inputFileName,
                               std::string treeName):
    RootTreeReader<hbb>(inputFileName,
                             treeName)
{
    initTree();
}


hbbReader::hbbReader(std::string inputFileName,
                               std::string directoryName,
                               std::string treeName):
    RootTreeReader<hbb>(inputFileName,
                             directoryName + std::string("/") + treeName)
{
    initTree();
}


hbbReader::~hbbReader()
{
}


void
hbbReader::initTree()
{

    // Set the branch addresses
    fChain.SetBranchAddress("nEvents", &nEvents, &b_nEvents);
    fChain.SetBranchAddress("evtNumber", &evtNumber, &b_evtNumber);
    fChain.SetBranchAddress("runNumber", &runNumber, &b_runNumber);
    fChain.SetBranchAddress("lumiBlock", &lumiBlock, &b_lumiBlock);
    fChain.SetBranchAddress("hasGoodPV", &hasGoodPV, &b_hasGoodPV);
    fChain.SetBranchAddress("SMTtags", &SMTtags, &b_SMTtags);
    fChain.SetBranchAddress("HLT_IsoMu13_v4_trig", &HLT_IsoMu13_v4_trig, &b_HLT_IsoMu13_v4_trig);
    fChain.SetBranchAddress("HLT_IsoMu15_v4_trig", &HLT_IsoMu15_v4_trig, &b_HLT_IsoMu15_v4_trig);
    fChain.SetBranchAddress("HLT_IsoMu17_v4_trig", &HLT_IsoMu17_v4_trig, &b_HLT_IsoMu17_v4_trig);
    fChain.SetBranchAddress("HLT_IsoMu17_v5_trig", &HLT_IsoMu17_v5_trig, &b_HLT_IsoMu17_v5_trig);
    fChain.SetBranchAddress("HLT_IsoMu17_v6_trig", &HLT_IsoMu17_v6_trig, &b_HLT_IsoMu17_v6_trig);
    fChain.SetBranchAddress("HLT_IsoMu17_v7_trig", &HLT_IsoMu17_v7_trig, &b_HLT_IsoMu17_v7_trig);
    fChain.SetBranchAddress("HLT_IsoMu17_v8_trig", &HLT_IsoMu17_v8_trig, &b_HLT_IsoMu17_v8_trig);
    fChain.SetBranchAddress("HLT_CentralJet80_MET80_trig", &HLT_CentralJet80_MET80_trig, &b_HLT_CentralJet80_MET80_trig);
    fChain.SetBranchAddress("HLT_pfMHT150_trig", &HLT_pfMHT150_trig, &b_HLT_pfMHT150_trig);
    fChain.SetBranchAddress("HLT_L1_ETM30_trig", &HLT_L1_ETM30_trig, &b_HLT_L1_ETM30_trig);
    fChain.SetBranchAddress("HLT_MET100_trig", &HLT_MET100_trig, &b_HLT_MET100_trig);
    fChain.SetBranchAddress("nJets", &nJets, &b_nJets);
    fChain.SetBranchAddress("nMuons", &nMuons, &b_nMuons);
    fChain.SetBranchAddress("nRawJets", &nRawJets, &b_nRawJets);
    fChain.SetBranchAddress("nRawMuons", &nRawMuons, &b_nRawMuons);
    fChain.SetBranchAddress("jetPt", jetPt, &b_jetPt);
    fChain.SetBranchAddress("jetEta", jetEta, &b_jetEta);
    fChain.SetBranchAddress("jetPhi", jetPhi, &b_jetPhi);
    fChain.SetBranchAddress("jetPx", jetPx, &b_jetPx);
    fChain.SetBranchAddress("jetPy", jetPy, &b_jetPy);
    fChain.SetBranchAddress("jetPz", jetPz, &b_jetPz);
    fChain.SetBranchAddress("jetP", jetP, &b_jetP);
    fChain.SetBranchAddress("jetFlavour", jetFlavour, &b_jetFlavour);
    fChain.SetBranchAddress("jetNumberOfDaughters", jetNumberOfDaughters, &b_jetNumberOfDaughters);
    fChain.SetBranchAddress("jetChargedMultiplicity", jetChargedMultiplicity, &b_jetChargedMultiplicity);
    fChain.SetBranchAddress("jetChargedEmEnergyFraction", jetChargedEmEnergyFraction, &b_jetChargedEmEnergyFraction);
    fChain.SetBranchAddress("jetNeutralHadronEnergyFraction", jetNeutralHadronEnergyFraction, &b_jetNeutralHadronEnergyFraction);
    fChain.SetBranchAddress("jetNeutralEmEnergyFraction", jetNeutralEmEnergyFraction, &b_jetNeutralEmEnergyFraction);
    fChain.SetBranchAddress("jetChargedHadronEnergyFraction", jetChargedHadronEnergyFraction, &b_jetChargedHadronEnergyFraction);
    fChain.SetBranchAddress("muonPt", muonPt, &b_muonPt);
    fChain.SetBranchAddress("muonEta", muonEta, &b_muonEta);
    fChain.SetBranchAddress("muonPhi", muonPhi, &b_muonPhi);
    fChain.SetBranchAddress("muonP", muonP, &b_muonP);
    fChain.SetBranchAddress("muonPx", muonPx, &b_muonPx);
    fChain.SetBranchAddress("muonPy", muonPy, &b_muonPy);
    fChain.SetBranchAddress("muonPz", muonPz, &b_muonPz);
    fChain.SetBranchAddress("isGlobalMuon", isGlobalMuon, &b_isGlobalMuon);
    fChain.SetBranchAddress("isTrackerMuon", isTrackerMuon, &b_isTrackerMuon);
    fChain.SetBranchAddress("muonNormalizedChi2", muonNormalizedChi2, &b_muonNormalizedChi2);
    fChain.SetBranchAddress("muonDB", muonDB, &b_muonDB);
    fChain.SetBranchAddress("muonTrackIso", muonTrackIso, &b_muonTrackIso);
    fChain.SetBranchAddress("muonCaloIso", muonCaloIso, &b_muonCaloIso);
    fChain.SetBranchAddress("muonNumberOfValidTrackerHits", muonNumberOfValidTrackerHits, &b_muonNumberOfValidTrackerHits);
    fChain.SetBranchAddress("muonNumberOfValidPixelHits", muonNumberOfValidPixelHits, &b_muonNumberOfValidPixelHits);
    fChain.SetBranchAddress("muonNumberOfValidMuonHits", muonNumberOfValidMuonHits, &b_muonNumberOfValidMuonHits);
    fChain.SetBranchAddress("muonNumberOfMatches", muonNumberOfMatches, &b_muonNumberOfMatches);
    fChain.SetBranchAddress("SMTevent", &SMTevent, &b_SMTevent);
    fChain.SetBranchAddress("bDisc_TCHE", bDisc_TCHE, &b_bDisc_TCHE);
    fChain.SetBranchAddress("bDisc_TCHP", bDisc_TCHP, &b_bDisc_TCHP);
    fChain.SetBranchAddress("bDisc_SSVHE", bDisc_SSVHE, &b_bDisc_SSVHE);
    fChain.SetBranchAddress("bDisc_SSVHP", bDisc_SSVHP, &b_bDisc_SSVHP);
    fChain.SetBranchAddress("bDisc_CSV", bDisc_CSV, &b_bDisc_CSV);
    fChain.SetBranchAddress("bDisc_JP", bDisc_JP, &b_bDisc_JP);
    fChain.SetBranchAddress("bDisc_JBP", bDisc_JBP, &b_bDisc_JBP);
    fChain.SetBranchAddress("bDisc_SMT", bDisc_SMT, &b_bDisc_SMT);
    fChain.SetBranchAddress("bDisc_SMTIP3dB", bDisc_SMTIP3dB, &b_bDisc_SMTIP3dB);
    fChain.SetBranchAddress("bDisc_SMTPt", bDisc_SMTPt, &b_bDisc_SMTPt);
    fChain.SetBranchAddress("bDisc_SETIP3dB", bDisc_SETIP3dB, &b_bDisc_SETIP3dB);
    fChain.SetBranchAddress("bDisc_SETPt", bDisc_SETPt, &b_bDisc_SETPt);
    fChain.SetBranchAddress("bDisc_CSVMVA", bDisc_CSVMVA, &b_bDisc_CSVMVA);
    fChain.SetBranchAddress("smt_jet", smt_jet, &b_smt_jet);
    fChain.SetBranchAddress("MetPFSumEt", &MetPFSumEt, &b_MetPFSumEt);
    fChain.SetBranchAddress("MetPFmEtSig", &MetPFmEtSig, &b_MetPFmEtSig);
    fChain.SetBranchAddress("MetPFPx", &MetPFPx, &b_MetPFPx);
    fChain.SetBranchAddress("MetPFPy", &MetPFPy, &b_MetPFPy);
    fChain.SetBranchAddress("MetPFPz", &MetPFPz, &b_MetPFPz);
    fChain.SetBranchAddress("MetPFPt", &MetPFPt, &b_MetPFPt);
    fChain.SetBranchAddress("MetPFPhi", &MetPFPhi, &b_MetPFPhi);
    fChain.SetBranchAddress("MetPFEta", &MetPFEta, &b_MetPFEta);
    fChain.SetBranchAddress("muIsPVcompatible", muIsPVcompatible, &b_muIsPVcompatible);
    fChain.SetBranchAddress("dR_isoMu_jet", dR_isoMu_jet, &b_dR_isoMu_jet);
    fChain.SetBranchAddress("MCHstatus", &MCHstatus, &b_MCHstatus);
    fChain.SetBranchAddress("MCHmomid", &MCHmomid, &b_MCHmomid);
    fChain.SetBranchAddress("MCHGmomid", &MCHGmomid, &b_MCHGmomid);
    fChain.SetBranchAddress("MCHpt", &MCHpt, &b_MCHpt);
    fChain.SetBranchAddress("MCHeta", &MCHeta, &b_MCHeta);
    fChain.SetBranchAddress("MCHphi", &MCHphi, &b_MCHphi);
    fChain.SetBranchAddress("MCHmass", &MCHmass, &b_MCHmass);
    fChain.SetBranchAddress("MCHndau", &MCHndau, &b_MCHndau);
    fChain.SetBranchAddress("MCHdauid", MCHdauid, &b_MCHdauid);
    fChain.SetBranchAddress("MCHdaupt", MCHdaupt, &b_MCHdaupt);
    fChain.SetBranchAddress("MCHdaueta", MCHdaueta, &b_MCHdaueta);
    fChain.SetBranchAddress("MCHdauphi", MCHdauphi, &b_MCHdauphi);
    fChain.SetBranchAddress("MCZstatus", &MCZstatus, &b_MCZstatus);
    fChain.SetBranchAddress("MCZmomid", &MCZmomid, &b_MCZmomid);
    fChain.SetBranchAddress("MCZGmomid", &MCZGmomid, &b_MCZGmomid);
    fChain.SetBranchAddress("MCZcharge", &MCZcharge, &b_MCZcharge);
    fChain.SetBranchAddress("MCZpt", &MCZpt, &b_MCZpt);
    fChain.SetBranchAddress("MCZeta", &MCZeta, &b_MCZeta);
    fChain.SetBranchAddress("MCZphi", &MCZphi, &b_MCZphi);
    fChain.SetBranchAddress("MCZmass", &MCZmass, &b_MCZmass);
    fChain.SetBranchAddress("MCZndau", &MCZndau, &b_MCZndau);
    fChain.SetBranchAddress("MCZdauid", MCZdauid, &b_MCZdauid);
    fChain.SetBranchAddress("MCZdaupt", MCZdaupt, &b_MCZdaupt);
    fChain.SetBranchAddress("MCZdaueta", MCZdaueta, &b_MCZdaueta);
    fChain.SetBranchAddress("MCZdauphi", MCZdauphi, &b_MCZdauphi);
    fChain.SetBranchAddress("MCbstatus", &MCbstatus, &b_MCbstatus);
    fChain.SetBranchAddress("MCbmomid", &MCbmomid, &b_MCbmomid);
    fChain.SetBranchAddress("MCbGmomid", &MCbGmomid, &b_MCbGmomid);
    fChain.SetBranchAddress("MCbpt", &MCbpt, &b_MCbpt);
    fChain.SetBranchAddress("MCbeta", &MCbeta, &b_MCbeta);
    fChain.SetBranchAddress("MCbphi", &MCbphi, &b_MCbphi);
    fChain.SetBranchAddress("MCbpx", &MCbpx, &b_MCbpx);
    fChain.SetBranchAddress("MCbpy", &MCbpy, &b_MCbpy);
    fChain.SetBranchAddress("MCbpz", &MCbpz, &b_MCbpz);
    fChain.SetBranchAddress("MCbE", &MCbE, &b_MCbE);
    fChain.SetBranchAddress("MCbbarstatus", &MCbbarstatus, &b_MCbbarstatus);
    fChain.SetBranchAddress("MCbbarmomid", &MCbbarmomid, &b_MCbbarmomid);
    fChain.SetBranchAddress("MCbbarGmomid", &MCbbarGmomid, &b_MCbbarGmomid);
    fChain.SetBranchAddress("MCbbarpt", &MCbbarpt, &b_MCbbarpt);
    fChain.SetBranchAddress("MCbbareta", &MCbbareta, &b_MCbbareta);
    fChain.SetBranchAddress("MCbbarphi", &MCbbarphi, &b_MCbbarphi);
    fChain.SetBranchAddress("MCbbarpx", &MCbbarpx, &b_MCbbarpx);
    fChain.SetBranchAddress("MCbbarpy", &MCbbarpy, &b_MCbbarpy);
    fChain.SetBranchAddress("MCbbarpz", &MCbbarpz, &b_MCbbarpz);
    fChain.SetBranchAddress("MCbbarE", &MCbbarE, &b_MCbbarE);
    fChain.SetBranchAddress("MCHDaubNdau", &MCHDaubNdau, &b_MCHDaubNdau);
    fChain.SetBranchAddress("MCHDaubdaupt", MCHDaubdaupt, &b_MCHDaubdaupt);
    fChain.SetBranchAddress("MCHDaubdaueta", MCHDaubdaueta, &b_MCHDaubdaueta);
    fChain.SetBranchAddress("MCHDaubdauphi", MCHDaubdauphi, &b_MCHDaubdauphi);
    fChain.SetBranchAddress("MCHDaubdaupx", MCHDaubdaupx, &b_MCHDaubdaupx);
    fChain.SetBranchAddress("MCHDaubdaupy", MCHDaubdaupy, &b_MCHDaubdaupy);
    fChain.SetBranchAddress("MCHDaubdaupz", MCHDaubdaupz, &b_MCHDaubdaupz);
    fChain.SetBranchAddress("MCHDaubdauE", MCHDaubdauE, &b_MCHDaubdauE);
    fChain.SetBranchAddress("MCHDaubbarNdau", &MCHDaubbarNdau, &b_MCHDaubbarNdau);
    fChain.SetBranchAddress("MCHDaubbardaupt", MCHDaubbardaupt, &b_MCHDaubbardaupt);
    fChain.SetBranchAddress("MCHDaubbardaueta", MCHDaubbardaueta, &b_MCHDaubbardaueta);
    fChain.SetBranchAddress("MCHDaubbardauphi", MCHDaubbardauphi, &b_MCHDaubbardauphi);
    fChain.SetBranchAddress("MCHDaubbardaupx", MCHDaubbardaupx, &b_MCHDaubbardaupx);
    fChain.SetBranchAddress("MCHDaubbardaupy", MCHDaubbardaupy, &b_MCHDaubbardaupy);
    fChain.SetBranchAddress("MCHDaubbardaupz", MCHDaubbardaupz, &b_MCHDaubbardaupz);
    fChain.SetBranchAddress("MCHDaubbardauE", MCHDaubbardauE, &b_MCHDaubbardauE);
    fChain.SetBranchAddress("MCccstatus", &MCccstatus, &b_MCccstatus);
    fChain.SetBranchAddress("MCccmomid", &MCccmomid, &b_MCccmomid);
    fChain.SetBranchAddress("MCccGmomid", &MCccGmomid, &b_MCccGmomid);

}
