/**
    @file tree.cc

    @brief This file is automatically generated from ROOT file /mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/malbouis/Hbb/HbbNtuples/Nov10Ntuple/Nov10Ntuple_PUFix_Fall11_2011AandB_OK/Updated_DiJetPt_ZH_ZToLL_HToBB_M-115_7TeV-powheg-herwigppProcV1_Fall11.root
    on Wed Dec  7 11:46:23 UTC 2011 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed Dec  7 11:46:23 UTC 2011

    $Id: tree.cc,v 1.3 2010/09/29 15:12:59 haryo Exp $
 */


#include<UserCode/wilken/interface/tree.h>


tree::tree()
{
}


tree::~tree()
{
}
