/**
    @file tree.cc

    @brief This file is automatically generated from ROOT file /home/hep/wilken/CMSSW_6_0_0/src/TMVA/TestSummer11ZH125.root
    on Wed Oct 24 13:32:56 UTC 2012 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed Oct 24 13:32:56 UTC 2012

    $Id: tree.cc,v 1.3 2010/09/29 15:12:59 haryo Exp $
 */


#include<UserCode/wilken/interface/tree.h>


tree::tree()
{
}


tree::~tree()
{
}
