/**
    @file tree.cc

    @brief This file is automatically generated from ROOT file /home/hep/wilken/CMSSW_5_3_3_patch2/src/VHbbAnalysis/VHbbDataFormats/bin/AdddedRootFiles/ZH_ZToLL_125HToBB.root
    on Mon Dec 17 10:03:34 UTC 2012 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Mon Dec 17 10:03:34 UTC 2012

    $Id: tree.cc,v 1.3 2010/09/29 15:12:59 haryo Exp $
 */


#include<UserCode/wilken/interface/tree.h>


tree::tree()
{
}


tree::~tree()
{
}
