/**
    @file treeReader.cc

    @brief This file is automatically generated from ROOT file /home/hep/wilken/CMSSW_5_3_3_patch2/src/VHbbAnalysis/VHbbDataFormats/bin/AdddedRootFiles/ZH_ZToLL_125HToBB.root
    on Mon Dec 17 10:03:34 UTC 2012 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Mon Dec 17 10:03:34 UTC 2012

    $Id: treeReader.cc,v 1.5 2010/09/29 15:13:14 haryo Exp $
 */


#include<UserCode/wilken/interface/treeReader.h>


treeReader::treeReader(std::string inputFileName,
                               std::string treeName):
    RootTreeReader<tree>(inputFileName,
                             treeName)
{
    initTree();
}


treeReader::treeReader(std::string inputFileName,
                               std::string directoryName,
                               std::string treeName):
    RootTreeReader<tree>(inputFileName,
                             directoryName + std::string("/") + treeName)
{
    initTree();
}


treeReader::~treeReader()
{
}


void
treeReader::initTree()
{

    // Set the branch addresses
    fChain.SetBranchAddress("H", &H_HiggsFlag, &b_H);
    fChain.SetBranchAddress("V", &V_mass, &b_V);
    fChain.SetBranchAddress("FatH", &FatH_FatHiggsFlag, &b_FatH);
    fChain.SetBranchAddress("lheV_pt", &lheV_pt, &b_lheV_pt);
    fChain.SetBranchAddress("lheHT", &lheHT, &b_lheHT);
    fChain.SetBranchAddress("lheNj", &lheNj, &b_lheNj);
    fChain.SetBranchAddress("genZ", &genZ_mass, &b_genZ);
    fChain.SetBranchAddress("genZstar", &genZstar_mass, &b_genZstar);
    fChain.SetBranchAddress("genW", &genW_mass, &b_genW);
    fChain.SetBranchAddress("genWstar", &genWstar_mass, &b_genWstar);
    fChain.SetBranchAddress("genH", &genH_mass, &b_genH);
    fChain.SetBranchAddress("genB", &genB_mass, &b_genB);
    fChain.SetBranchAddress("genBbar", &genBbar_mass, &b_genBbar);
    fChain.SetBranchAddress("genTop", &genTop_bmass, &b_genTop);
    fChain.SetBranchAddress("genTbar", &genTbar_bmass, &b_genTbar);
    fChain.SetBranchAddress("TkSharing", &TkSharing_HiggsCSVtkSharing, &b_TkSharing);
    fChain.SetBranchAddress("nhJets", &nhJets, &b_nhJets);
    fChain.SetBranchAddress("nfathFilterJets", &nfathFilterJets, &b_nfathFilterJets);
    fChain.SetBranchAddress("naJets", &naJets, &b_naJets);
    fChain.SetBranchAddress("hJet_pt", hJet_pt, &b_hJet_pt);
    fChain.SetBranchAddress("hJet_eta", hJet_eta, &b_hJet_eta);
    fChain.SetBranchAddress("hJet_phi", hJet_phi, &b_hJet_phi);
    fChain.SetBranchAddress("hJet_e", hJet_e, &b_hJet_e);
    fChain.SetBranchAddress("hJet_csv", hJet_csv, &b_hJet_csv);
    fChain.SetBranchAddress("hJet_csv_nominal", hJet_csv_nominal, &b_hJet_csv_nominal);
    fChain.SetBranchAddress("hJet_csv_upBC", hJet_csv_upBC, &b_hJet_csv_upBC);
    fChain.SetBranchAddress("hJet_csv_downBC", hJet_csv_downBC, &b_hJet_csv_downBC);
    fChain.SetBranchAddress("hJet_csv_upL", hJet_csv_upL, &b_hJet_csv_upL);
    fChain.SetBranchAddress("hJet_csv_downL", hJet_csv_downL, &b_hJet_csv_downL);
    fChain.SetBranchAddress("hJet_csv_nominal4p", hJet_csv_nominal4p, &b_hJet_csv_nominal4p);
    fChain.SetBranchAddress("hJet_csv_upBC4p", hJet_csv_upBC4p, &b_hJet_csv_upBC4p);
    fChain.SetBranchAddress("hJet_csv_downBC4p", hJet_csv_downBC4p, &b_hJet_csv_downBC4p);
    fChain.SetBranchAddress("hJet_csvivf", hJet_csvivf, &b_hJet_csvivf);
    fChain.SetBranchAddress("hJet_cmva", hJet_cmva, &b_hJet_cmva);
    fChain.SetBranchAddress("hJet_cosTheta", hJet_cosTheta, &b_hJet_cosTheta);
    fChain.SetBranchAddress("hJet_numTracksSV", hJet_numTracksSV, &b_hJet_numTracksSV);
    fChain.SetBranchAddress("hJet_chf", hJet_chf, &b_hJet_chf);
    fChain.SetBranchAddress("hJet_nhf", hJet_nhf, &b_hJet_nhf);
    fChain.SetBranchAddress("hJet_cef", hJet_cef, &b_hJet_cef);
    fChain.SetBranchAddress("hJet_nef", hJet_nef, &b_hJet_nef);
    fChain.SetBranchAddress("hJet_nch", hJet_nch, &b_hJet_nch);
    fChain.SetBranchAddress("hJet_nconstituents", hJet_nconstituents, &b_hJet_nconstituents);
    fChain.SetBranchAddress("hJet_flavour", hJet_flavour, &b_hJet_flavour);
    fChain.SetBranchAddress("hJet_isSemiLept", hJet_isSemiLept, &b_hJet_isSemiLept);
    fChain.SetBranchAddress("hJet_isSemiLeptMCtruth", hJet_isSemiLeptMCtruth, &b_hJet_isSemiLeptMCtruth);
    fChain.SetBranchAddress("hJet_SoftLeptpdgId", hJet_SoftLeptpdgId, &b_hJet_SoftLeptpdgId);
    fChain.SetBranchAddress("hJet_SoftLeptIdlooseMu", hJet_SoftLeptIdlooseMu, &b_hJet_SoftLeptIdlooseMu);
    fChain.SetBranchAddress("hJet_SoftLeptId95", hJet_SoftLeptId95, &b_hJet_SoftLeptId95);
    fChain.SetBranchAddress("hJet_SoftLeptPt", hJet_SoftLeptPt, &b_hJet_SoftLeptPt);
    fChain.SetBranchAddress("hJet_SoftLeptdR", hJet_SoftLeptdR, &b_hJet_SoftLeptdR);
    fChain.SetBranchAddress("hJet_SoftLeptptRel", hJet_SoftLeptptRel, &b_hJet_SoftLeptptRel);
    fChain.SetBranchAddress("hJet_SoftLeptRelCombIso", hJet_SoftLeptRelCombIso, &b_hJet_SoftLeptRelCombIso);
    fChain.SetBranchAddress("hJet_genPt", hJet_genPt, &b_hJet_genPt);
    fChain.SetBranchAddress("hJet_genEta", hJet_genEta, &b_hJet_genEta);
    fChain.SetBranchAddress("hJet_genPhi", hJet_genPhi, &b_hJet_genPhi);
    fChain.SetBranchAddress("hJet_JECUnc", hJet_JECUnc, &b_hJet_JECUnc);
    fChain.SetBranchAddress("hJet_vtxMass", hJet_vtxMass, &b_hJet_vtxMass);
    fChain.SetBranchAddress("hJet_vtxPt", hJet_vtxPt, &b_hJet_vtxPt);
    fChain.SetBranchAddress("hJet_vtxEta", hJet_vtxEta, &b_hJet_vtxEta);
    fChain.SetBranchAddress("hJet_vtxPhi", hJet_vtxPhi, &b_hJet_vtxPhi);
    fChain.SetBranchAddress("hJet_vtxE", hJet_vtxE, &b_hJet_vtxE);
    fChain.SetBranchAddress("hJet_vtx3dL", hJet_vtx3dL, &b_hJet_vtx3dL);
    fChain.SetBranchAddress("hJet_vtx3deL", hJet_vtx3deL, &b_hJet_vtx3deL);
    fChain.SetBranchAddress("hJet_id", hJet_id, &b_hJet_id);
    fChain.SetBranchAddress("hJet_SF_CSVL", hJet_SF_CSVL, &b_hJet_SF_CSVL);
    fChain.SetBranchAddress("hJet_SF_CSVM", hJet_SF_CSVM, &b_hJet_SF_CSVM);
    fChain.SetBranchAddress("hJet_SF_CSVT", hJet_SF_CSVT, &b_hJet_SF_CSVT);
    fChain.SetBranchAddress("hJet_SF_CSVLerr", hJet_SF_CSVLerr, &b_hJet_SF_CSVLerr);
    fChain.SetBranchAddress("hJet_SF_CSVMerr", hJet_SF_CSVMerr, &b_hJet_SF_CSVMerr);
    fChain.SetBranchAddress("hJet_SF_CSVTerr", hJet_SF_CSVTerr, &b_hJet_SF_CSVTerr);
    fChain.SetBranchAddress("hJet_ptRaw", hJet_ptRaw, &b_hJet_ptRaw);
    fChain.SetBranchAddress("hJet_ptLeadTrack", hJet_ptLeadTrack, &b_hJet_ptLeadTrack);
    fChain.SetBranchAddress("hJet_puJetIdL", hJet_puJetIdL, &b_hJet_puJetIdL);
    fChain.SetBranchAddress("hJet_puJetIdM", hJet_puJetIdM, &b_hJet_puJetIdM);
    fChain.SetBranchAddress("hJet_puJetIdT", hJet_puJetIdT, &b_hJet_puJetIdT);
    fChain.SetBranchAddress("hJet_puJetIdMva", hJet_puJetIdMva, &b_hJet_puJetIdMva);
    fChain.SetBranchAddress("hJet_charge", hJet_charge, &b_hJet_charge);
    fChain.SetBranchAddress("fathFilterJets_pt", fathFilterJets_pt, &b_fathFilterJets_pt);
    fChain.SetBranchAddress("fathFilterJets_eta", fathFilterJets_eta, &b_fathFilterJets_eta);
    fChain.SetBranchAddress("fathFilterJets_phi", fathFilterJets_phi, &b_fathFilterJets_phi);
    fChain.SetBranchAddress("fathFilterJets_e", fathFilterJets_e, &b_fathFilterJets_e);
    fChain.SetBranchAddress("fathFilterJets_csv", fathFilterJets_csv, &b_fathFilterJets_csv);
    fChain.SetBranchAddress("fathFilterJets_chf", fathFilterJets_chf, &b_fathFilterJets_chf);
    fChain.SetBranchAddress("fathFilterJets_ptRaw", fathFilterJets_ptRaw, &b_fathFilterJets_ptRaw);
    fChain.SetBranchAddress("fathFilterJets_ptLeadTrack", fathFilterJets_ptLeadTrack, &b_fathFilterJets_ptLeadTrack);
    fChain.SetBranchAddress("fathFilterJets_flavour", fathFilterJets_flavour, &b_fathFilterJets_flavour);
    fChain.SetBranchAddress("fathFilterJets_isSemiLept", fathFilterJets_isSemiLept, &b_fathFilterJets_isSemiLept);
    fChain.SetBranchAddress("fathFilterJets_isSemiLeptMCtruth", fathFilterJets_isSemiLeptMCtruth, &b_fathFilterJets_isSemiLeptMCtruth);
    fChain.SetBranchAddress("fathFilterJets_genPt", fathFilterJets_genPt, &b_fathFilterJets_genPt);
    fChain.SetBranchAddress("fathFilterJets_genEta", fathFilterJets_genEta, &b_fathFilterJets_genEta);
    fChain.SetBranchAddress("fathFilterJets_genPhi", fathFilterJets_genPhi, &b_fathFilterJets_genPhi);
    fChain.SetBranchAddress("fathFilterJets_vtxMass", fathFilterJets_vtxMass, &b_fathFilterJets_vtxMass);
    fChain.SetBranchAddress("fathFilterJets_vtx3dL", fathFilterJets_vtx3dL, &b_fathFilterJets_vtx3dL);
    fChain.SetBranchAddress("fathFilterJets_vtx3deL", fathFilterJets_vtx3deL, &b_fathFilterJets_vtx3deL);
    fChain.SetBranchAddress("fathFilterJets_vtxPt", fathFilterJets_vtxPt, &b_fathFilterJets_vtxPt);
    fChain.SetBranchAddress("fathFilterJets_vtxEta", fathFilterJets_vtxEta, &b_fathFilterJets_vtxEta);
    fChain.SetBranchAddress("fathFilterJets_vtxPhi", fathFilterJets_vtxPhi, &b_fathFilterJets_vtxPhi);
    fChain.SetBranchAddress("fathFilterJets_vtxE", fathFilterJets_vtxE, &b_fathFilterJets_vtxE);
    fChain.SetBranchAddress("fathFilterJets_csvivf", fathFilterJets_csvivf, &b_fathFilterJets_csvivf);
    fChain.SetBranchAddress("fathFilterJets_cmva", fathFilterJets_cmva, &b_fathFilterJets_cmva);
    fChain.SetBranchAddress("fathFilterJets_cosTheta", fathFilterJets_cosTheta, &b_fathFilterJets_cosTheta);
    fChain.SetBranchAddress("fathFilterJets_jetArea", fathFilterJets_jetArea, &b_fathFilterJets_jetArea);
    fChain.SetBranchAddress("aJet_pt", aJet_pt, &b_aJet_pt);
    fChain.SetBranchAddress("aJet_eta", aJet_eta, &b_aJet_eta);
    fChain.SetBranchAddress("aJet_phi", aJet_phi, &b_aJet_phi);
    fChain.SetBranchAddress("aJet_e", aJet_e, &b_aJet_e);
    fChain.SetBranchAddress("aJet_csv", aJet_csv, &b_aJet_csv);
    fChain.SetBranchAddress("aJet_csv_nominal", aJet_csv_nominal, &b_aJet_csv_nominal);
    fChain.SetBranchAddress("aJet_csv_upBC", aJet_csv_upBC, &b_aJet_csv_upBC);
    fChain.SetBranchAddress("aJet_csv_downBC", aJet_csv_downBC, &b_aJet_csv_downBC);
    fChain.SetBranchAddress("aJet_csv_upL", aJet_csv_upL, &b_aJet_csv_upL);
    fChain.SetBranchAddress("aJet_csv_downL", aJet_csv_downL, &b_aJet_csv_downL);
    fChain.SetBranchAddress("aJet_csv_nominal4p", aJet_csv_nominal4p, &b_aJet_csv_nominal4p);
    fChain.SetBranchAddress("aJet_csv_upBC4p", aJet_csv_upBC4p, &b_aJet_csv_upBC4p);
    fChain.SetBranchAddress("aJet_csv_downBC4p", aJet_csv_downBC4p, &b_aJet_csv_downBC4p);
    fChain.SetBranchAddress("aJet_csvivf", aJet_csvivf, &b_aJet_csvivf);
    fChain.SetBranchAddress("aJet_cmva", aJet_cmva, &b_aJet_cmva);
    fChain.SetBranchAddress("aJet_cosTheta", aJet_cosTheta, &b_aJet_cosTheta);
    fChain.SetBranchAddress("aJet_numTracksSV", aJet_numTracksSV, &b_aJet_numTracksSV);
    fChain.SetBranchAddress("aJet_chf", aJet_chf, &b_aJet_chf);
    fChain.SetBranchAddress("aJet_nhf", aJet_nhf, &b_aJet_nhf);
    fChain.SetBranchAddress("aJet_cef", aJet_cef, &b_aJet_cef);
    fChain.SetBranchAddress("aJet_nef", aJet_nef, &b_aJet_nef);
    fChain.SetBranchAddress("aJet_nch", aJet_nch, &b_aJet_nch);
    fChain.SetBranchAddress("aJet_nconstituents", aJet_nconstituents, &b_aJet_nconstituents);
    fChain.SetBranchAddress("aJet_flavour", aJet_flavour, &b_aJet_flavour);
    fChain.SetBranchAddress("aJet_isSemiLept", aJet_isSemiLept, &b_aJet_isSemiLept);
    fChain.SetBranchAddress("aJet_isSemiLeptMCtruth", aJet_isSemiLeptMCtruth, &b_aJet_isSemiLeptMCtruth);
    fChain.SetBranchAddress("aJet_SoftLeptpdgId", aJet_SoftLeptpdgId, &b_aJet_SoftLeptpdgId);
    fChain.SetBranchAddress("aJet_SoftLeptIdlooseMu", aJet_SoftLeptIdlooseMu, &b_aJet_SoftLeptIdlooseMu);
    fChain.SetBranchAddress("aJet_SoftLeptId95", aJet_SoftLeptId95, &b_aJet_SoftLeptId95);
    fChain.SetBranchAddress("aJet_SoftLeptPt", aJet_SoftLeptPt, &b_aJet_SoftLeptPt);
    fChain.SetBranchAddress("aJet_SoftLeptdR", aJet_SoftLeptdR, &b_aJet_SoftLeptdR);
    fChain.SetBranchAddress("aJet_SoftLeptptRel", aJet_SoftLeptptRel, &b_aJet_SoftLeptptRel);
    fChain.SetBranchAddress("aJet_SoftLeptRelCombIso", aJet_SoftLeptRelCombIso, &b_aJet_SoftLeptRelCombIso);
    fChain.SetBranchAddress("aJet_puJetIdL", aJet_puJetIdL, &b_aJet_puJetIdL);
    fChain.SetBranchAddress("aJet_puJetIdM", aJet_puJetIdM, &b_aJet_puJetIdM);
    fChain.SetBranchAddress("aJet_puJetIdT", aJet_puJetIdT, &b_aJet_puJetIdT);
    fChain.SetBranchAddress("aJet_puJetIdMva", aJet_puJetIdMva, &b_aJet_puJetIdMva);
    fChain.SetBranchAddress("aJet_charge", aJet_charge, &b_aJet_charge);
    fChain.SetBranchAddress("aJet_genPt", aJet_genPt, &b_aJet_genPt);
    fChain.SetBranchAddress("aJet_genEta", aJet_genEta, &b_aJet_genEta);
    fChain.SetBranchAddress("aJet_genPhi", aJet_genPhi, &b_aJet_genPhi);
    fChain.SetBranchAddress("aJet_JECUnc", aJet_JECUnc, &b_aJet_JECUnc);
    fChain.SetBranchAddress("aJet_vtxMass", aJet_vtxMass, &b_aJet_vtxMass);
    fChain.SetBranchAddress("aJet_vtx3dL", aJet_vtx3dL, &b_aJet_vtx3dL);
    fChain.SetBranchAddress("aJet_vtx3deL", aJet_vtx3deL, &b_aJet_vtx3deL);
    fChain.SetBranchAddress("aJet_id", aJet_id, &b_aJet_id);
    fChain.SetBranchAddress("aJet_SF_CSVL", aJet_SF_CSVL, &b_aJet_SF_CSVL);
    fChain.SetBranchAddress("aJet_SF_CSVM", aJet_SF_CSVM, &b_aJet_SF_CSVM);
    fChain.SetBranchAddress("aJet_SF_CSVT", aJet_SF_CSVT, &b_aJet_SF_CSVT);
    fChain.SetBranchAddress("aJet_SF_CSVLerr", aJet_SF_CSVLerr, &b_aJet_SF_CSVLerr);
    fChain.SetBranchAddress("aJet_SF_CSVMerr", aJet_SF_CSVMerr, &b_aJet_SF_CSVMerr);
    fChain.SetBranchAddress("aJet_SF_CSVTerr", aJet_SF_CSVTerr, &b_aJet_SF_CSVTerr);
    fChain.SetBranchAddress("naJetsFat", &naJetsFat, &b_naJetsFat);
    fChain.SetBranchAddress("aJetFat_pt", aJetFat_pt, &b_aJetFat_pt);
    fChain.SetBranchAddress("aJetFat_eta", aJetFat_eta, &b_aJetFat_eta);
    fChain.SetBranchAddress("aJetFat_phi", aJetFat_phi, &b_aJetFat_phi);
    fChain.SetBranchAddress("aJetFat_e", aJetFat_e, &b_aJetFat_e);
    fChain.SetBranchAddress("aJetFat_csv", aJetFat_csv, &b_aJetFat_csv);
    fChain.SetBranchAddress("numJets", &numJets, &b_numJets);
    fChain.SetBranchAddress("numBJets", &numBJets, &b_numBJets);
    fChain.SetBranchAddress("deltaPullAngle", &deltaPullAngle, &b_deltaPullAngle);
    fChain.SetBranchAddress("deltaPullAngle2", &deltaPullAngle2, &b_deltaPullAngle2);
    fChain.SetBranchAddress("gendrcc", &gendrcc, &b_gendrcc);
    fChain.SetBranchAddress("gendrbb", &gendrbb, &b_gendrbb);
    fChain.SetBranchAddress("genZpt", &genZpt, &b_genZpt);
    fChain.SetBranchAddress("genWpt", &genWpt, &b_genWpt);
    fChain.SetBranchAddress("genHpt", &genHpt, &b_genHpt);
    fChain.SetBranchAddress("weightTrig", &weightTrig, &b_weightTrig);
    fChain.SetBranchAddress("weightTrigMay", &weightTrigMay, &b_weightTrigMay);
    fChain.SetBranchAddress("weightTrigV4", &weightTrigV4, &b_weightTrigV4);
    fChain.SetBranchAddress("weightTrigMET", &weightTrigMET, &b_weightTrigMET);
    fChain.SetBranchAddress("weightTrigOrMu30", &weightTrigOrMu30, &b_weightTrigOrMu30);
    fChain.SetBranchAddress("weightEleRecoAndId", &weightEleRecoAndId, &b_weightEleRecoAndId);
    fChain.SetBranchAddress("weightEleTrigJetMETPart", &weightEleTrigJetMETPart, &b_weightEleTrigJetMETPart);
    fChain.SetBranchAddress("weightEleTrigElePart", &weightEleTrigElePart, &b_weightEleTrigElePart);
    fChain.SetBranchAddress("weightEleTrigEleAugPart", &weightEleTrigEleAugPart, &b_weightEleTrigEleAugPart);
    fChain.SetBranchAddress("weightTrigMET80", &weightTrigMET80, &b_weightTrigMET80);
    fChain.SetBranchAddress("weightTrigMET100", &weightTrigMET100, &b_weightTrigMET100);
    fChain.SetBranchAddress("weightTrig2CJet20", &weightTrig2CJet20, &b_weightTrig2CJet20);
    fChain.SetBranchAddress("weightTrigMET150", &weightTrigMET150, &b_weightTrigMET150);
    fChain.SetBranchAddress("weightTrigMET802CJet", &weightTrigMET802CJet, &b_weightTrigMET802CJet);
    fChain.SetBranchAddress("weightTrigMET1002CJet", &weightTrigMET1002CJet, &b_weightTrigMET1002CJet);
    fChain.SetBranchAddress("weightTrigMETLP", &weightTrigMETLP, &b_weightTrigMETLP);
    fChain.SetBranchAddress("weightTrig2012A", &weightTrig2012A, &b_weightTrig2012A);
    fChain.SetBranchAddress("weightTrig2012ADiMuon", &weightTrig2012ADiMuon, &b_weightTrig2012ADiMuon);
    fChain.SetBranchAddress("weightTrig2012ADiEle", &weightTrig2012ADiEle, &b_weightTrig2012ADiEle);
    fChain.SetBranchAddress("weightTrig2012ASingleMuon", &weightTrig2012ASingleMuon, &b_weightTrig2012ASingleMuon);
    fChain.SetBranchAddress("weightTrig2012ASingleEle", &weightTrig2012ASingleEle, &b_weightTrig2012ASingleEle);
    fChain.SetBranchAddress("weightTrig2012AMuonPlusWCandPt", &weightTrig2012AMuonPlusWCandPt, &b_weightTrig2012AMuonPlusWCandPt);
    fChain.SetBranchAddress("weightTrig2012", &weightTrig2012, &b_weightTrig2012);
    fChain.SetBranchAddress("weightTrig2012DiMuon", &weightTrig2012DiMuon, &b_weightTrig2012DiMuon);
    fChain.SetBranchAddress("weightTrig2012DiEle", &weightTrig2012DiEle, &b_weightTrig2012DiEle);
    fChain.SetBranchAddress("weightTrig2012SingleMuon", &weightTrig2012SingleMuon, &b_weightTrig2012SingleMuon);
    fChain.SetBranchAddress("weightTrig2012SingleEle", &weightTrig2012SingleEle, &b_weightTrig2012SingleEle);
    fChain.SetBranchAddress("weightTrig2012MuonPlusWCandPt", &weightTrig2012MuonPlusWCandPt, &b_weightTrig2012MuonPlusWCandPt);
    fChain.SetBranchAddress("weightTrig2012AB", &weightTrig2012AB, &b_weightTrig2012AB);
    fChain.SetBranchAddress("weightTrig2012ABDiMuon", &weightTrig2012ABDiMuon, &b_weightTrig2012ABDiMuon);
    fChain.SetBranchAddress("weightTrig2012ABDiEle", &weightTrig2012ABDiEle, &b_weightTrig2012ABDiEle);
    fChain.SetBranchAddress("weightTrig2012ABSingleMuon", &weightTrig2012ABSingleMuon, &b_weightTrig2012ABSingleMuon);
    fChain.SetBranchAddress("weightTrig2012ABSingleEle", &weightTrig2012ABSingleEle, &b_weightTrig2012ABSingleEle);
    fChain.SetBranchAddress("weightTrig2012ABMuonPlusWCandPt", &weightTrig2012ABMuonPlusWCandPt, &b_weightTrig2012ABMuonPlusWCandPt);
    fChain.SetBranchAddress("weightTrig2012DiJet30MHT80", &weightTrig2012DiJet30MHT80, &b_weightTrig2012DiJet30MHT80);
    fChain.SetBranchAddress("weightTrig2012PFMET150", &weightTrig2012PFMET150, &b_weightTrig2012PFMET150);
    fChain.SetBranchAddress("weightTrig2012SumpT100MET100", &weightTrig2012SumpT100MET100, &b_weightTrig2012SumpT100MET100);
    fChain.SetBranchAddress("weightTrig2012APFMET150orDiJetMET", &weightTrig2012APFMET150orDiJetMET, &b_weightTrig2012APFMET150orDiJetMET);
    fChain.SetBranchAddress("weightTrig2012BPFMET150orDiJetMET", &weightTrig2012BPFMET150orDiJetMET, &b_weightTrig2012BPFMET150orDiJetMET);
    fChain.SetBranchAddress("weightTrig2012CPFMET150orDiJetMET", &weightTrig2012CPFMET150orDiJetMET, &b_weightTrig2012CPFMET150orDiJetMET);
    fChain.SetBranchAddress("deltaPullAngleAK7", &deltaPullAngleAK7, &b_deltaPullAngleAK7);
    fChain.SetBranchAddress("deltaPullAngle2AK7", &deltaPullAngle2AK7, &b_deltaPullAngle2AK7);
    fChain.SetBranchAddress("PU0", &PU0, &b_PU0);
    fChain.SetBranchAddress("PUm1", &PUm1, &b_PUm1);
    fChain.SetBranchAddress("PUp1", &PUp1, &b_PUp1);
    fChain.SetBranchAddress("PUweight", &PUweight, &b_PUweight);
    fChain.SetBranchAddress("PUweight2011B", &PUweight2011B, &b_PUweight2011B);
    fChain.SetBranchAddress("PUweight1DObs", &PUweight1DObs, &b_PUweight1DObs);
    fChain.SetBranchAddress("eventFlav", &eventFlav, &b_eventFlav);
    fChain.SetBranchAddress("Vtype", &Vtype, &b_Vtype);
    fChain.SetBranchAddress("HVdPhi", &HVdPhi, &b_HVdPhi);
    fChain.SetBranchAddress("HVMass", &HVMass, &b_HVMass);
    fChain.SetBranchAddress("HMETdPhi", &HMETdPhi, &b_HMETdPhi);
    fChain.SetBranchAddress("VMt", &VMt, &b_VMt);
    fChain.SetBranchAddress("VMtmu", &VMtmu, &b_VMtmu);
    fChain.SetBranchAddress("VMte", &VMte, &b_VMte);
    fChain.SetBranchAddress("nvlep", &nvlep, &b_nvlep);
    fChain.SetBranchAddress("nalep", &nalep, &b_nalep);
    fChain.SetBranchAddress("vLepton_mass", vLepton_mass, &b_vLepton_mass);
    fChain.SetBranchAddress("vLepton_pt", vLepton_pt, &b_vLepton_pt);
    fChain.SetBranchAddress("vLepton_eta", vLepton_eta, &b_vLepton_eta);
    fChain.SetBranchAddress("vLepton_phi", vLepton_phi, &b_vLepton_phi);
    fChain.SetBranchAddress("vLepton_aodCombRelIso", vLepton_aodCombRelIso, &b_vLepton_aodCombRelIso);
    fChain.SetBranchAddress("vLepton_pfCombRelIso", vLepton_pfCombRelIso, &b_vLepton_pfCombRelIso);
    fChain.SetBranchAddress("vLepton_photonIso", vLepton_photonIso, &b_vLepton_photonIso);
    fChain.SetBranchAddress("vLepton_neutralHadIso", vLepton_neutralHadIso, &b_vLepton_neutralHadIso);
    fChain.SetBranchAddress("vLepton_chargedHadIso", vLepton_chargedHadIso, &b_vLepton_chargedHadIso);
    fChain.SetBranchAddress("vLepton_chargedPUIso", vLepton_chargedPUIso, &b_vLepton_chargedPUIso);
    fChain.SetBranchAddress("vLepton_particleIso", vLepton_particleIso, &b_vLepton_particleIso);
    fChain.SetBranchAddress("vLepton_dxy", vLepton_dxy, &b_vLepton_dxy);
    fChain.SetBranchAddress("vLepton_dz", vLepton_dz, &b_vLepton_dz);
    fChain.SetBranchAddress("vLepton_type", vLepton_type, &b_vLepton_type);
    fChain.SetBranchAddress("vLepton_id80", vLepton_id80, &b_vLepton_id80);
    fChain.SetBranchAddress("vLepton_id95", vLepton_id95, &b_vLepton_id95);
    fChain.SetBranchAddress("vLepton_vbtf", vLepton_vbtf, &b_vLepton_vbtf);
    fChain.SetBranchAddress("vLepton_id80NoIso", vLepton_id80NoIso, &b_vLepton_id80NoIso);
    fChain.SetBranchAddress("vLepton_genPt", vLepton_genPt, &b_vLepton_genPt);
    fChain.SetBranchAddress("vLepton_genEta", vLepton_genEta, &b_vLepton_genEta);
    fChain.SetBranchAddress("vLepton_genPhi", vLepton_genPhi, &b_vLepton_genPhi);
    fChain.SetBranchAddress("vLepton_charge", vLepton_charge, &b_vLepton_charge);
    fChain.SetBranchAddress("vLepton_acop", vLepton_acop, &b_vLepton_acop);
    fChain.SetBranchAddress("vLepton_pfCorrIso", vLepton_pfCorrIso, &b_vLepton_pfCorrIso);
    fChain.SetBranchAddress("vLepton_id2012tight", vLepton_id2012tight, &b_vLepton_id2012tight);
    fChain.SetBranchAddress("vLepton_idMVAnotrig", vLepton_idMVAnotrig, &b_vLepton_idMVAnotrig);
    fChain.SetBranchAddress("vLepton_idMVAtrig", vLepton_idMVAtrig, &b_vLepton_idMVAtrig);
    fChain.SetBranchAddress("vLepton_idMVApresel", vLepton_idMVApresel, &b_vLepton_idMVApresel);
    fChain.SetBranchAddress("vLepton_innerHits", vLepton_innerHits, &b_vLepton_innerHits);
    fChain.SetBranchAddress("vLepton_photonIsoDoubleCount", vLepton_photonIsoDoubleCount, &b_vLepton_photonIsoDoubleCount);
    fChain.SetBranchAddress("vLepton_wpHWW", vLepton_wpHWW, &b_vLepton_wpHWW);
    fChain.SetBranchAddress("vLepton_wp95", vLepton_wp95, &b_vLepton_wp95);
    fChain.SetBranchAddress("vLepton_wp90", vLepton_wp90, &b_vLepton_wp90);
    fChain.SetBranchAddress("vLepton_wp85", vLepton_wp85, &b_vLepton_wp85);
    fChain.SetBranchAddress("vLepton_wp80", vLepton_wp80, &b_vLepton_wp80);
    fChain.SetBranchAddress("vLepton_wp70", vLepton_wp70, &b_vLepton_wp70);
    fChain.SetBranchAddress("aLepton_mass", aLepton_mass, &b_aLepton_mass);
    fChain.SetBranchAddress("aLepton_pt", aLepton_pt, &b_aLepton_pt);
    fChain.SetBranchAddress("aLepton_eta", aLepton_eta, &b_aLepton_eta);
    fChain.SetBranchAddress("aLepton_phi", aLepton_phi, &b_aLepton_phi);
    fChain.SetBranchAddress("aLepton_aodCombRelIso", aLepton_aodCombRelIso, &b_aLepton_aodCombRelIso);
    fChain.SetBranchAddress("aLepton_pfCombRelIso", aLepton_pfCombRelIso, &b_aLepton_pfCombRelIso);
    fChain.SetBranchAddress("aLepton_photonIso", aLepton_photonIso, &b_aLepton_photonIso);
    fChain.SetBranchAddress("aLepton_neutralHadIso", aLepton_neutralHadIso, &b_aLepton_neutralHadIso);
    fChain.SetBranchAddress("aLepton_chargedHadIso", aLepton_chargedHadIso, &b_aLepton_chargedHadIso);
    fChain.SetBranchAddress("aLepton_chargedPUIso", aLepton_chargedPUIso, &b_aLepton_chargedPUIso);
    fChain.SetBranchAddress("aLepton_particleIso", aLepton_particleIso, &b_aLepton_particleIso);
    fChain.SetBranchAddress("aLepton_dxy", aLepton_dxy, &b_aLepton_dxy);
    fChain.SetBranchAddress("aLepton_dz", aLepton_dz, &b_aLepton_dz);
    fChain.SetBranchAddress("aLepton_type", aLepton_type, &b_aLepton_type);
    fChain.SetBranchAddress("aLepton_id80", aLepton_id80, &b_aLepton_id80);
    fChain.SetBranchAddress("aLepton_id95", aLepton_id95, &b_aLepton_id95);
    fChain.SetBranchAddress("aLepton_vbtf", aLepton_vbtf, &b_aLepton_vbtf);
    fChain.SetBranchAddress("aLepton_id80NoIso", aLepton_id80NoIso, &b_aLepton_id80NoIso);
    fChain.SetBranchAddress("aLepton_genPt", aLepton_genPt, &b_aLepton_genPt);
    fChain.SetBranchAddress("aLepton_genEta", aLepton_genEta, &b_aLepton_genEta);
    fChain.SetBranchAddress("aLepton_genPhi", aLepton_genPhi, &b_aLepton_genPhi);
    fChain.SetBranchAddress("aLepton_charge", aLepton_charge, &b_aLepton_charge);
    fChain.SetBranchAddress("aLepton_acop", aLepton_acop, &b_aLepton_acop);
    fChain.SetBranchAddress("aLepton_pfCorrIso", aLepton_pfCorrIso, &b_aLepton_pfCorrIso);
    fChain.SetBranchAddress("aLepton_id2012tight", aLepton_id2012tight, &b_aLepton_id2012tight);
    fChain.SetBranchAddress("aLepton_idMVAnotrig", aLepton_idMVAnotrig, &b_aLepton_idMVAnotrig);
    fChain.SetBranchAddress("aLepton_idMVAtrig", aLepton_idMVAtrig, &b_aLepton_idMVAtrig);
    fChain.SetBranchAddress("aLepton_idMVApresel", aLepton_idMVApresel, &b_aLepton_idMVApresel);
    fChain.SetBranchAddress("aLepton_innerHits", aLepton_innerHits, &b_aLepton_innerHits);
    fChain.SetBranchAddress("aLepton_photonIsoDoubleCount", aLepton_photonIsoDoubleCount, &b_aLepton_photonIsoDoubleCount);
    fChain.SetBranchAddress("aLepton_wpHWW", aLepton_wpHWW, &b_aLepton_wpHWW);
    fChain.SetBranchAddress("aLepton_wp95", aLepton_wp95, &b_aLepton_wp95);
    fChain.SetBranchAddress("aLepton_wp90", aLepton_wp90, &b_aLepton_wp90);
    fChain.SetBranchAddress("aLepton_wp85", aLepton_wp85, &b_aLepton_wp85);
    fChain.SetBranchAddress("aLepton_wp80", aLepton_wp80, &b_aLepton_wp80);
    fChain.SetBranchAddress("aLepton_wp70", aLepton_wp70, &b_aLepton_wp70);
    fChain.SetBranchAddress("top", &top_mass, &b_top);
    fChain.SetBranchAddress("WplusMode", &WplusMode, &b_WplusMode);
    fChain.SetBranchAddress("WminusMode", &WminusMode, &b_WminusMode);
    fChain.SetBranchAddress("nSvs", &nSvs, &b_nSvs);
    fChain.SetBranchAddress("Sv_massBCand", Sv_massBCand, &b_Sv_massBCand);
    fChain.SetBranchAddress("Sv_massSv", Sv_massSv, &b_Sv_massSv);
    fChain.SetBranchAddress("Sv_pt", Sv_pt, &b_Sv_pt);
    fChain.SetBranchAddress("Sv_eta", Sv_eta, &b_Sv_eta);
    fChain.SetBranchAddress("Sv_phi", Sv_phi, &b_Sv_phi);
    fChain.SetBranchAddress("Sv_dist3D", Sv_dist3D, &b_Sv_dist3D);
    fChain.SetBranchAddress("Sv_dist2D", Sv_dist2D, &b_Sv_dist2D);
    fChain.SetBranchAddress("Sv_distSim2D", Sv_distSim2D, &b_Sv_distSim2D);
    fChain.SetBranchAddress("Sv_distSig3D", Sv_distSig3D, &b_Sv_distSig3D);
    fChain.SetBranchAddress("Sv_dist3D_norm", Sv_dist3D_norm, &b_Sv_dist3D_norm);
    fChain.SetBranchAddress("SVH", &SVH_mass, &b_SVH);
    fChain.SetBranchAddress("nSimBs", &nSimBs, &b_nSimBs);
    fChain.SetBranchAddress("SimBs_mass", SimBs_mass, &b_SimBs_mass);
    fChain.SetBranchAddress("SimBs_pt", SimBs_pt, &b_SimBs_pt);
    fChain.SetBranchAddress("SimBs_eta", SimBs_eta, &b_SimBs_eta);
    fChain.SetBranchAddress("SimBs_phi", SimBs_phi, &b_SimBs_phi);
    fChain.SetBranchAddress("SimBs_vtx_x", SimBs_vtx_x, &b_SimBs_vtx_x);
    fChain.SetBranchAddress("SimBs_vtx_y", SimBs_vtx_y, &b_SimBs_vtx_y);
    fChain.SetBranchAddress("SimBs_vtx_z", SimBs_vtx_z, &b_SimBs_vtx_z);
    fChain.SetBranchAddress("SimBs_pdgId", SimBs_pdgId, &b_SimBs_pdgId);
    fChain.SetBranchAddress("SimBs_status", SimBs_status, &b_SimBs_status);
    fChain.SetBranchAddress("SimBsH", &SimBsH_mass, &b_SimBsH);
    fChain.SetBranchAddress("rho", &rho, &b_rho);
    fChain.SetBranchAddress("rho25", &rho25, &b_rho25);
    fChain.SetBranchAddress("rhoN", &rhoN, &b_rhoN);
    fChain.SetBranchAddress("nPVs", &nPVs, &b_nPVs);
    fChain.SetBranchAddress("METnoPU", &METnoPU_et, &b_METnoPU);
    fChain.SetBranchAddress("METnoPUCh", &METnoPUCh_et, &b_METnoPUCh);
    fChain.SetBranchAddress("MET", &MET_et, &b_MET);
    fChain.SetBranchAddress("METtype1corr", &METtype1corr_et, &b_METtype1corr);
    fChain.SetBranchAddress("METtype1p2corr", &METtype1p2corr_et, &b_METtype1p2corr);
    fChain.SetBranchAddress("METnoPUtype1corr", &METnoPUtype1corr_et, &b_METnoPUtype1corr);
    fChain.SetBranchAddress("METnoPUtype1p2corr", &METnoPUtype1p2corr_et, &b_METnoPUtype1p2corr);
    fChain.SetBranchAddress("metUnc_et", metUnc_et, &b_et);
    fChain.SetBranchAddress("metUnc_phi", metUnc_phi, &b_phi);
    fChain.SetBranchAddress("metUnc_sumet", metUnc_sumet, &b_sumet);
    fChain.SetBranchAddress("fakeMET", &fakeMET_et, &b_fakeMET);
    fChain.SetBranchAddress("MHT", &MHT_mht, &b_MHT);
    fChain.SetBranchAddress("minDeltaPhijetMET", &minDeltaPhijetMET, &b_minDeltaPhijetMET);
    fChain.SetBranchAddress("minDeltaPhijetMETZtau", &minDeltaPhijetMETZtau, &b_minDeltaPhijetMETZtau);
    fChain.SetBranchAddress("jetPt_minDeltaPhijetMET", &jetPt_minDeltaPhijetMET, &b_jetPt_minDeltaPhijetMET);
    fChain.SetBranchAddress("CovMartixfirst", &CovMartixfirst, &b_CovMartixfirst);
    fChain.SetBranchAddress("CovMartixsecond", &CovMartixsecond, &b_CovMartixsecond);
    fChain.SetBranchAddress("CovMatrixCorrelation", &CovMatrixCorrelation, &b_CovMatrixCorrelation);
    fChain.SetBranchAddress("svmass", &svmass, &b_svmass);
    fChain.SetBranchAddress("PzetaVis", &PzetaVis, &b_PzetaVis);
    fChain.SetBranchAddress("PzetaMiss", &PzetaMiss, &b_PzetaMiss);
    fChain.SetBranchAddress("Pzeta25", &Pzeta25, &b_Pzeta25);
    fChain.SetBranchAddress("Pzeta45", &Pzeta45, &b_Pzeta45);
    fChain.SetBranchAddress("Pzeta65", &Pzeta65, &b_Pzeta65);
    fChain.SetBranchAddress("Pzeta85", &Pzeta85, &b_Pzeta85);
    fChain.SetBranchAddress("triggerFlags", triggerFlags, &b_triggerFlags);
    fChain.SetBranchAddress("EVENT", &EVENT_run, &b_EVENT);
    fChain.SetBranchAddress("hbhe", &hbhe, &b_hbhe);
    fChain.SetBranchAddress("totalKinematics", &totalKinematics, &b_totalKinematics);
    fChain.SetBranchAddress("ecalFlag", &ecalFlag, &b_ecalFlag);
    fChain.SetBranchAddress("cschaloFlag", &cschaloFlag, &b_cschaloFlag);
    fChain.SetBranchAddress("hcallaserFlag", &hcallaserFlag, &b_hcallaserFlag);
    fChain.SetBranchAddress("trackingfailureFlag", &trackingfailureFlag, &b_trackingfailureFlag);
    fChain.SetBranchAddress("eebadscFlag", &eebadscFlag, &b_eebadscFlag);
    fChain.SetBranchAddress("btag1TSF", &btag1TSF, &b_btag1TSF);
    fChain.SetBranchAddress("btag2TSF", &btag2TSF, &b_btag2TSF);
    fChain.SetBranchAddress("btag1T2CSF", &btag1T2CSF, &b_btag1T2CSF);
    fChain.SetBranchAddress("btag2CSF", &btag2CSF, &b_btag2CSF);
    fChain.SetBranchAddress("btagA0CSF", &btagA0CSF, &b_btagA0CSF);
    fChain.SetBranchAddress("btagA0TSF", &btagA0TSF, &b_btagA0TSF);
    fChain.SetBranchAddress("btag1TA1C", &btag1TA1C, &b_btag1TA1C);
    fChain.SetBranchAddress("vLepton_decayModeFinding", vLepton_decayModeFinding, &b_vLepton_decayModeFinding);
    fChain.SetBranchAddress("vLepton_byLooseCombinedIsolationDeltaBetaCorr", vLepton_byLooseCombinedIsolationDeltaBetaCorr, &b_vLepton_byLooseCombinedIsolationDeltaBetaCorr);
    fChain.SetBranchAddress("vLepton_againstMuonTight", vLepton_againstMuonTight, &b_vLepton_againstMuonTight);
    fChain.SetBranchAddress("vLepton_againstElectronLoose", vLepton_againstElectronLoose, &b_vLepton_againstElectronLoose);
    fChain.SetBranchAddress("vLepton_againstElectronMedium", vLepton_againstElectronMedium, &b_vLepton_againstElectronMedium);
    fChain.SetBranchAddress("vLepton_againstElectronMVA", vLepton_againstElectronMVA, &b_vLepton_againstElectronMVA);
    fChain.SetBranchAddress("vLepton_NsignalPFChargedHadrCands", vLepton_NsignalPFChargedHadrCands, &b_vLepton_NsignalPFChargedHadrCands);
    fChain.SetBranchAddress("vLepton_NsignalPFGammaCands", vLepton_NsignalPFGammaCands, &b_vLepton_NsignalPFGammaCands);
    fChain.SetBranchAddress("vLepton_leadPFChargedHadrCandPt", vLepton_leadPFChargedHadrCandPt, &b_vLepton_leadPFChargedHadrCandPt);
    fChain.SetBranchAddress("vLepton_byLooseIsolation", vLepton_byLooseIsolation, &b_vLepton_byLooseIsolation);
    fChain.SetBranchAddress("vLepton_byMediumIsolation", vLepton_byMediumIsolation, &b_vLepton_byMediumIsolation);
    fChain.SetBranchAddress("vLepton_byTightIsolation", vLepton_byTightIsolation, &b_vLepton_byTightIsolation);
    fChain.SetBranchAddress("aLepton_decayModeFinding", aLepton_decayModeFinding, &b_aLepton_decayModeFinding);
    fChain.SetBranchAddress("aLepton_byLooseCombinedIsolationDeltaBetaCorr", aLepton_byLooseCombinedIsolationDeltaBetaCorr, &b_aLepton_byLooseCombinedIsolationDeltaBetaCorr);
    fChain.SetBranchAddress("aLepton_againstMuonTight", aLepton_againstMuonTight, &b_aLepton_againstMuonTight);
    fChain.SetBranchAddress("aLepton_againstElectronLoose", aLepton_againstElectronLoose, &b_aLepton_againstElectronLoose);
    fChain.SetBranchAddress("aLepton_againstElectronMedium", aLepton_againstElectronMedium, &b_aLepton_againstElectronMedium);
    fChain.SetBranchAddress("aLepton_againstElectronMVA", aLepton_againstElectronMVA, &b_aLepton_againstElectronMVA);
    fChain.SetBranchAddress("aLepton_NsignalPFChargedHadrCands", aLepton_NsignalPFChargedHadrCands, &b_aLepton_NsignalPFChargedHadrCands);
    fChain.SetBranchAddress("aLepton_NsignalPFGammaCands", aLepton_NsignalPFGammaCands, &b_aLepton_NsignalPFGammaCands);
    fChain.SetBranchAddress("aLepton_leadPFChargedHadrCandPt", aLepton_leadPFChargedHadrCandPt, &b_aLepton_leadPFChargedHadrCandPt);
    fChain.SetBranchAddress("aLepton_byLooseIsolation", aLepton_byLooseIsolation, &b_aLepton_byLooseIsolation);
    fChain.SetBranchAddress("aLepton_byMediumIsolation", aLepton_byMediumIsolation, &b_aLepton_byMediumIsolation);
    fChain.SetBranchAddress("aLepton_byTightIsolation", aLepton_byTightIsolation, &b_aLepton_byTightIsolation);
    fChain.SetBranchAddress("aJet_selectedTauDR", aJet_selectedTauDR, &b_aJet_selectedTauDR);
    fChain.SetBranchAddress("tauPlusMode", &tauPlusMode, &b_tauPlusMode);
    fChain.SetBranchAddress("tauMinusMode", &tauMinusMode, &b_tauMinusMode);
    fChain.SetBranchAddress("isMostlyGarbage", &isMostlyGarbage, &b_isMostlyGarbage);

}
