/**
    @file treeReader.cc

    @brief This file is automatically generated from ROOT file
 /mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/malbouis/Hbb/HbbNtuples/oct9Ntuple/
 TestZH_ZToLL_HToBB_M-115_7TeV-powheg-herwigpp.root
    on Wed Oct 26 23:24:15 UTC 2011 by the script createReader.py.

    @warning
    Users may need to edit the content of this file to fit their needs.

    @date Wed Oct 26 23:24:15 UTC 2011

 */


#include<UserCode/wilken/interface/treeReader.h>


treeReader::treeReader(std::string inputFileName,
                               std::string treeName):
    RootTreeReader<tree>(inputFileName,
                             treeName)
{
    initTree();
}


treeReader::treeReader(std::string inputFileName,
                               std::string directoryName,
                               std::string treeName):
    RootTreeReader<tree>(inputFileName,
                             directoryName + std::string("/") + treeName)
{
    initTree();
}


treeReader::~treeReader()
{
}


void
treeReader::initTree()
{

    // Set the branch addresses
    fChain.SetBranchAddress("H", &H_mass, &b_H);
    fChain.SetBranchAddress("V", &V_mass, &b_V);
    fChain.SetBranchAddress("nhJets", &nhJets, &b_nhJets);
    fChain.SetBranchAddress("naJets", &naJets, &b_naJets);
    fChain.SetBranchAddress("hJet_pt", hJet_pt, &b_hJet_pt);
    fChain.SetBranchAddress("hJet_eta", hJet_eta, &b_hJet_eta);
    fChain.SetBranchAddress("hJet_phi", hJet_phi, &b_hJet_phi);
    fChain.SetBranchAddress("hJet_csv", hJet_csv, &b_hJet_csv);
    fChain.SetBranchAddress("hJet_cosTheta", hJet_cosTheta, &b_hJet_cosTheta);
    fChain.SetBranchAddress("hJet_numTracksSV", hJet_numTracksSV, &b_hJet_numTracksSV);
    fChain.SetBranchAddress("hJet_chf", hJet_chf, &b_hJet_chf);
    fChain.SetBranchAddress("hJet_nhf", hJet_nhf, &b_hJet_nhf);
    fChain.SetBranchAddress("hJet_cef", hJet_cef, &b_hJet_cef);
    fChain.SetBranchAddress("hJet_nef", hJet_nef, &b_hJet_nef);
    fChain.SetBranchAddress("hJet_nch", hJet_nch, &b_hJet_nch);
    fChain.SetBranchAddress("hJet_nconstituents", hJet_nconstituents, &b_hJet_nconstituents);
    fChain.SetBranchAddress("hJet_flavour", hJet_flavour, &b_hJet_flavour);
    fChain.SetBranchAddress("hJet_genPt", hJet_genPt, &b_hJet_genPt);
    fChain.SetBranchAddress("hJet_genEta", hJet_genEta, &b_hJet_genEta);
    fChain.SetBranchAddress("hJet_genPhi", hJet_genPhi, &b_hJet_genPhi);
    fChain.SetBranchAddress("hJet_JECUnc", hJet_JECUnc, &b_hJet_JECUnc);
    fChain.SetBranchAddress("hJet_vtxMass", hJet_vtxMass, &b_hJet_vtxMass);
    fChain.SetBranchAddress("hJet_vtx3dL", hJet_vtx3dL, &b_hJet_vtx3dL);
    fChain.SetBranchAddress("hJet_vtx3deL", hJet_vtx3deL, &b_hJet_vtx3deL);
    fChain.SetBranchAddress("hJet_id", hJet_id, &b_hJet_id);
    fChain.SetBranchAddress("aJet_pt", aJet_pt, &b_aJet_pt);
    fChain.SetBranchAddress("aJet_eta", aJet_eta, &b_aJet_eta);
    fChain.SetBranchAddress("aJet_phi", aJet_phi, &b_aJet_phi);
    fChain.SetBranchAddress("aJet_csv", aJet_csv, &b_aJet_csv);
    fChain.SetBranchAddress("aJet_cosTheta", aJet_cosTheta, &b_aJet_cosTheta);
    fChain.SetBranchAddress("aJet_numTracksSV", aJet_numTracksSV, &b_aJet_numTracksSV);
    fChain.SetBranchAddress("aJet_chf", aJet_chf, &b_aJet_chf);
    fChain.SetBranchAddress("aJet_nhf", aJet_nhf, &b_aJet_nhf);
    fChain.SetBranchAddress("aJet_cef", aJet_cef, &b_aJet_cef);
    fChain.SetBranchAddress("aJet_nef", aJet_nef, &b_aJet_nef);
    fChain.SetBranchAddress("aJet_nch", aJet_nch, &b_aJet_nch);
    fChain.SetBranchAddress("aJet_nconstituents", aJet_nconstituents, &b_aJet_nconstituents);
    fChain.SetBranchAddress("aJet_flavour", aJet_flavour, &b_aJet_flavour);
    fChain.SetBranchAddress("aJet_genPt", aJet_genPt, &b_aJet_genPt);
    fChain.SetBranchAddress("aJet_genEta", aJet_genEta, &b_aJet_genEta);
    fChain.SetBranchAddress("aJet_genPhi", aJet_genPhi, &b_aJet_genPhi);
    fChain.SetBranchAddress("aJet_JECUnc", aJet_JECUnc, &b_aJet_JECUnc);
    fChain.SetBranchAddress("aJet_vtxMass", aJet_vtxMass, &b_aJet_vtxMass);
    fChain.SetBranchAddress("aJet_vtx3dL", aJet_vtx3dL, &b_aJet_vtx3dL);
    fChain.SetBranchAddress("aJet_vtx3deL", aJet_vtx3deL, &b_aJet_vtx3deL);
    fChain.SetBranchAddress("aJet_id", aJet_id, &b_aJet_id);
    fChain.SetBranchAddress("numJets", &numJets, &b_numJets);
    fChain.SetBranchAddress("numBJets", &numBJets, &b_numBJets);
    fChain.SetBranchAddress("deltaPullAngle", &deltaPullAngle, &b_deltaPullAngle);
    fChain.SetBranchAddress("gendrcc", &gendrcc, &b_gendrcc);
    fChain.SetBranchAddress("gendrbb", &gendrbb, &b_gendrbb);
    fChain.SetBranchAddress("genZpt", &genZpt, &b_genZpt);
    fChain.SetBranchAddress("genWpt", &genWpt, &b_genWpt);
    fChain.SetBranchAddress("weightTrig", &weightTrig, &b_weightTrig);
    fChain.SetBranchAddress("weightTrigMay", &weightTrigMay, &b_weightTrigMay);
    fChain.SetBranchAddress("weightTrigV4", &weightTrigV4, &b_weightTrigV4);
    fChain.SetBranchAddress("weightTrigMET", &weightTrigMET, &b_weightTrigMET);
    fChain.SetBranchAddress("weightEleRecoAndId", &weightEleRecoAndId, &b_weightEleRecoAndId);
    fChain.SetBranchAddress("weightEleTrigJetMETPart", &weightEleTrigJetMETPart, &b_weightEleTrigJetMETPart);
    fChain.SetBranchAddress("weightEleTrigElePart", &weightEleTrigElePart, &b_weightEleTrigElePart);
    fChain.SetBranchAddress("deltaPullAngleAK7", &deltaPullAngleAK7, &b_deltaPullAngleAK7);
    fChain.SetBranchAddress("PUweight", &PUweight, &b_PUweight);
    fChain.SetBranchAddress("eventFlav", &eventFlav, &b_eventFlav);
    fChain.SetBranchAddress("Vtype", &Vtype, &b_Vtype);
    fChain.SetBranchAddress("HVdPhi", &HVdPhi, &b_HVdPhi);
    fChain.SetBranchAddress("HVMass", &HVMass, &b_HVMass);
    fChain.SetBranchAddress("HMETdPhi", &HMETdPhi, &b_HMETdPhi);
    fChain.SetBranchAddress("VMt", &VMt, &b_VMt);
    fChain.SetBranchAddress("nvlep", &nvlep, &b_nvlep);
    fChain.SetBranchAddress("nalep", &nalep, &b_nalep);
    fChain.SetBranchAddress("vLepton_mass", vLepton_mass, &b_vLepton_mass);
    fChain.SetBranchAddress("vLepton_pt", vLepton_pt, &b_vLepton_pt);
    fChain.SetBranchAddress("vLepton_eta", vLepton_eta, &b_vLepton_eta);
    fChain.SetBranchAddress("vLepton_phi", vLepton_phi, &b_vLepton_phi);
    fChain.SetBranchAddress("vLepton_aodCombRelIso", vLepton_aodCombRelIso, &b_vLepton_aodCombRelIso);
    fChain.SetBranchAddress("vLepton_pfCombRelIso", vLepton_pfCombRelIso, &b_vLepton_pfCombRelIso);
    fChain.SetBranchAddress("vLepton_photonIso", vLepton_photonIso, &b_vLepton_photonIso);
    fChain.SetBranchAddress("vLepton_neutralHadIso", vLepton_neutralHadIso, &b_vLepton_neutralHadIso);
    fChain.SetBranchAddress("vLepton_chargedHadIso", vLepton_chargedHadIso, &b_vLepton_chargedHadIso);
    fChain.SetBranchAddress("vLepton_particleIso", vLepton_particleIso, &b_vLepton_particleIso);
    fChain.SetBranchAddress("vLepton_dxy", vLepton_dxy, &b_vLepton_dxy);
    fChain.SetBranchAddress("vLepton_dz", vLepton_dz, &b_vLepton_dz);
    fChain.SetBranchAddress("vLepton_type", vLepton_type, &b_vLepton_type);
    fChain.SetBranchAddress("vLepton_id80", vLepton_id80, &b_vLepton_id80);
    fChain.SetBranchAddress("vLepton_id95", vLepton_id95, &b_vLepton_id95);
    fChain.SetBranchAddress("aLepton_mass", aLepton_mass, &b_aLepton_mass);
    fChain.SetBranchAddress("aLepton_pt", aLepton_pt, &b_aLepton_pt);
    fChain.SetBranchAddress("aLepton_eta", aLepton_eta, &b_aLepton_eta);
    fChain.SetBranchAddress("aLepton_phi", aLepton_phi, &b_aLepton_phi);
    fChain.SetBranchAddress("aLepton_aodCombRelIso", aLepton_aodCombRelIso, &b_aLepton_aodCombRelIso);
    fChain.SetBranchAddress("aLepton_pfCombRelIso", aLepton_pfCombRelIso, &b_aLepton_pfCombRelIso);
    fChain.SetBranchAddress("aLepton_photonIso", aLepton_photonIso, &b_aLepton_photonIso);
    fChain.SetBranchAddress("aLepton_neutralHadIso", aLepton_neutralHadIso, &b_aLepton_neutralHadIso);
    fChain.SetBranchAddress("aLepton_chargedHadIso", aLepton_chargedHadIso, &b_aLepton_chargedHadIso);
    fChain.SetBranchAddress("aLepton_particleIso", aLepton_particleIso, &b_aLepton_particleIso);
    fChain.SetBranchAddress("aLepton_dxy", aLepton_dxy, &b_aLepton_dxy);
    fChain.SetBranchAddress("aLepton_dz", aLepton_dz, &b_aLepton_dz);
    fChain.SetBranchAddress("aLepton_type", aLepton_type, &b_aLepton_type);
    fChain.SetBranchAddress("aLepton_id80", aLepton_id80, &b_aLepton_id80);
    fChain.SetBranchAddress("aLepton_id95", aLepton_id95, &b_aLepton_id95);
    fChain.SetBranchAddress("top", &top_mass, &b_top);
    fChain.SetBranchAddress("nSvs", &nSvs, &b_nSvs);
    fChain.SetBranchAddress("Sv_massBCand", Sv_massBCand, &b_Sv_massBCand);
    fChain.SetBranchAddress("Sv_massSv", Sv_massSv, &b_Sv_massSv);
    fChain.SetBranchAddress("Sv_pt", Sv_pt, &b_Sv_pt);
    fChain.SetBranchAddress("Sv_eta", Sv_eta, &b_Sv_eta);
    fChain.SetBranchAddress("Sv_phi", Sv_phi, &b_Sv_phi);
    fChain.SetBranchAddress("Sv_dist3D", Sv_dist3D, &b_Sv_dist3D);
    fChain.SetBranchAddress("Sv_dist2D", Sv_dist2D, &b_Sv_dist2D);
    fChain.SetBranchAddress("Sv_distSim2D", Sv_distSim2D, &b_Sv_distSim2D);
    fChain.SetBranchAddress("Sv_distSig3D", Sv_distSig3D, &b_Sv_distSig3D);
    fChain.SetBranchAddress("Sv_dist3D_norm", Sv_dist3D_norm, &b_Sv_dist3D_norm);
    fChain.SetBranchAddress("SVH", &SVH_mass, &b_SVH);
    fChain.SetBranchAddress("rho", &rho, &b_rho);
    fChain.SetBranchAddress("rho25", &rho25, &b_rho25);
    fChain.SetBranchAddress("nPVs", &nPVs, &b_nPVs);
    fChain.SetBranchAddress("METnoPU", &METnoPU_et, &b_METnoPU);
    fChain.SetBranchAddress("MET", &MET_et, &b_MET);
    fChain.SetBranchAddress("MHT", &MHT_mht, &b_MHT);
    fChain.SetBranchAddress("minDeltaPhijetMET", &minDeltaPhijetMET, &b_minDeltaPhijetMET);
    fChain.SetBranchAddress("jetPt_minDeltaPhijetMET", &jetPt_minDeltaPhijetMET, &b_jetPt_minDeltaPhijetMET);
    fChain.SetBranchAddress("triggerFlags", triggerFlags, &b_triggerFlags);
    fChain.SetBranchAddress("EVENT", &EVENT_run, &b_EVENT);
    fChain.SetBranchAddress("hbhe", &hbhe, &b_hbhe);
    fChain.SetBranchAddress("btag1TSF", &btag1TSF, &b_btag1TSF);
    fChain.SetBranchAddress("btag2TSF", &btag2TSF, &b_btag2TSF);
    fChain.SetBranchAddress("btag1T2CSF", &btag1T2CSF, &b_btag1T2CSF);
    fChain.SetBranchAddress("btag2CSF", &btag2CSF, &b_btag2CSF);
    fChain.SetBranchAddress("btagA0CSF", &btagA0CSF, &b_btagA0CSF);

}
